### ISSUE TITLE
SegmentFault when using coro::SpinLock

### ISSUE THREAD

**Issue by beef9999** [alibaba/async_simple#100]
Hi I was trying to add concurrency to the `async_echo_client.cpp`, so the socket send/recv would need lock projection.

However I met a SegmentFault when using coro::SpinLock, see https://github.com/alibaba/async_simple/pull/99

**Comment by qicosmos** [comment]
Could you provide more information, what compiler?

**Comment by beef9999** [comment]
gcc10 centos8.5

**Comment by beef9999** [comment]
Is there any problem with my code?

**Comment by ChuanqiXu9** [comment]
> Is there any problem with my code?

This might be a mis-use. We need to pass an executor in the start point of the async chain. But the diagnostic message from the library side is not friendly indeed. We would try to enhance it. Thanks for reporting.

**Comment by ChuanqiXu9** [comment]
This one should be fixed.
