### ISSUE TITLE
build failed for stdc++? 

### ISSUE THREAD

**Issue by hick** [alibaba/async_simple#117]
### Search before asking

done and found nothing helpful

### What happened + What you expected to happen

2 problems

* my version of googletest has change the name of gtest and gmock(yes, it maybe not a problem,  I just found it change to googletest and googlemock) , and have no "install" for make, 

![image](https://user-images.githubusercontent.com/38886/173190134-d0ee4c20-1be9-411a-93df-b165a3c7f2ab.png)

although the gtrest may be build successfully, but not for the gmock as the following

```
root@ehicku20:/usr/src/googletest/googlemock/build# make
make[1]: *** No rule to make target '../googletest/CMakeFiles/gtest.dir/all', needed by 'CMakeFiles/gmock.dir/all'.  Stop.
make: *** [Makefile:84: all] Error 2
root@ehicku20:/usr/src/googletest/googlemock/build# make install
make: *** No rule to make target 'install'.  Stop.
```

* failed to build for the last step, I tried to install the the lib "stdc++" ,   "apt-cache search stdc++" for lots of version, and installed some like "apt install libx32stdc++-9-dev-amd64-cross lib32stdc++-9-dev-amd64-cross" and some other versions, searched in google and found nothing else helpful,  failed at last

![image](https://user-images.githubusercontent.com/38886/173190029-28f9f441-f7f7-4e88-ac2a-d7d9a7b42d39.png)

### Reproduction way

just do  most steps as the instruction in the readme, my OS is ubuntu 20.04, and I installed clang11 clang12 for Rust some times ago. 

### Are you willing to submit a PR?

no

**Comment by RainMark** [comment]
>  "apt install libx32stdc++-9-dev-amd64-cross lib32stdc++-9-dev-amd64-cross" and some other versions,

@hick Your host is 32bit system? can your paste the `uname -a` output? 
Looks like should use `sudo apt-get install libstdc++6` to install libstdc++，have you tried？

**Comment by ChuanqiXu9** [comment]
For the gtest problem, could you try `mkdir build && cd build && cmake .. && make install`?

**Comment by hick** [comment]
thx a lot , I've destroyed that box of vagrant+virtulbox, and it works now in a brand new ubuntu 20.04 system:  I do not know the reason, maybe my old ubuntu 20 is something wrong
