### ISSUE TITLE
We need Bazel support

### ISSUE THREAD

**Issue by devillove084** [alibaba/async_simple#121]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
Given it might not be too complex, would you like to contribute it?

**Comment by ChuanqiXu9** [comment]
Supported in https://github.com/alibaba/async_simple/pull/176
