### ISSUE TITLE
The series function of collect* cause segment fault when param is a right reference to temporary object

### ISSUE THREAD

**Issue by poor-circle** [alibaba/async_simple#127]
### Search before asking

- [✔] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

The function collectAll/Any...  cause segment fault when param is a right reference to temporary object.

### Reproduction way
Just use temporary object as param in coroutine context.
```cpp
collectAll(Lazy<int>{},Lazy<float>{});
collectAll(std::vector<Lazy<int>>{});
//....
```

### Are you willing to submit a PR?

- [✔ ] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
May be we can just copy the lazy<T> to avoid this problem.

**Comment by yanminhui** [comment]
```.cpp
inline auto collectAll(LazyType<Ts>... inputs) -> Lazy<std::tuple<Try<Ts>...>> {
    if constexpr (0 == sizeof...(Ts)) {
        co_return std::tuple<>{};
    } else {
        co_return co_await detail::collectAllVariadicImpl<false>(
            std::make_index_sequence<sizeof...(Ts)>{}, std::move(inputs)...);
    }
}
```
