### ISSUE TITLE
build third-part libraries with cmake on vs

### ISSUE THREAD

**Issue by kcwl** [alibaba/async_simple#143]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
HI，cmake generate error when I use vs2022，would you consider fixing it?

`已为默认配置“x64-Debug”启动 CMake 生成。
1> 命令行: "C:\Windows\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "d:\vs2022\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="G:\git\async_simple\out\install\x64-Debug" -DCMAKE_C_COMPILER:FILEPATH="D:/vs2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="D:/vs2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="d:\vs2022\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "G:\git\async_simple" 2>&1"
1> 工作目录: G:\git\async_simple\out\build\x64-Debug
1> [CMake] -- The CXX compiler identification is MSVC 19.33.31629.0
1> [CMake] -- The C compiler identification is MSVC 19.33.31629.0
1> [CMake] -- The ASM compiler identification is MSVC
1> [CMake] -- Found assembler: D:/vs2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Check for working CXX compiler: D:/vs2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] -- Detecting C compiler ABI info
1> [CMake] -- Detecting C compiler ABI info - done
1> [CMake] -- Check for working C compiler: D:/vs2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting C compile features
1> [CMake] -- Detecting C compile features - done
1> [CMake] -- CMAKE_MODULE_PATH: G:/git/async_simple/cmake
1> [CMake] -- Looking for pthread.h
1> [CMake] -- Looking for pthread.h - not found
1> [CMake] -- Found Threads: TRUE  
1> [CMake] -- FindAio.cmake: 
1> [CMake] CMake Warning (dev) at D:/vs2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
1> [CMake]   The package name passed to `find_package_handle_standard_args` (aio) does
1> [CMake]   not match the name of the calling package (Aio).  This can lead to problems
1> [CMake]   in calling code that expects `find_package` result variables (e.g.,
1> [CMake]   `_FOUND`) to follow a certain pattern.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   cmake/FindAio.cmake:22 (find_package_handle_standard_args)
1> [CMake]   CMakeLists.txt:9 (find_package)
1> [CMake] This warning is for project developers.  Use -Wno-dev to suppress it.
1> [CMake] 
1> [CMake] -- Could NOT find aio (missing: LIBAIO_LIBRARIES) 
1> [CMake] CMake Warning (dev) at D:/vs2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
1> [CMake]   The package name passed to `find_package_handle_standard_args` (benchmark)
1> [CMake]   does not match the name of the calling package (Benchmark).  This can lead
1> [CMake]   to problems in calling code that expects `find_package` result variables
1> [CMake]   (e.g., `_FOUND`) to follow a certain pattern.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   cmake/FindBenchmark.cmake:25 (find_package_handle_standard_args)
1> [CMake]   CMakeLists.txt:11 (find_package)
1> [CMake] This warning is for project developers.  Use -Wno-dev to suppress it.
1> [CMake] 
1> [CMake] -- Could NOT find benchmark (missing: BENCHMARK_LIBRARIES BENCHMARK_INCLUDE_DIR) 
1> [CMake] CMake Warning (dev) at D:/vs2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
1> [CMake]   The package name passed to `find_package_handle_standard_args` (gmock) does
1> [CMake]   not match the name of the calling package (GMock).  This can lead to
1> [CMake]   problems in calling code that expects `find_package` result variables
1> [CMake]   (e.g., `_FOUND`) to follow a certain pattern.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   cmake/FindGMock.cmake:25 (find_package_handle_standard_args)
1> [CMake]   CMakeLists.txt:23 (find_package)
1> [CMake] This warning is for project developers.  Use -Wno-dev to suppress it.
1> [CMake] 
1> [CMake] -- Could NOT find gmock (missing: GMOCK_LIBRARIES GMOCK_INCLUDE_DIR) 
1> [CMake] CMake Warning (dev) at D:/vs2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
1> [CMake]   The package name passed to `find_package_handle_standard_args` (gtest) does
1> [CMake]   not match the name of the calling package (GTest).  This can lead to
1> [CMake]   problems in calling code that expects `find_package` result variables
1> [CMake]   (e.g., `_FOUND`) to follow a certain pattern.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   cmake/FindGTest.cmake:25 (find_package_handle_standard_args)
1> [CMake]   CMakeLists.txt:24 (find_package)
1> [CMake] This warning is for project developers.  Use -Wno-dev to suppress it.
1> [CMake] 
1> [CMake] -- Could NOT find gtest (missing: GTEST_LIBRARIES GTEST_INCLUDE_DIR) 
1> [CMake] CMake Error at G:\git\async_simple\CMakeLists.txt:30 (message):
1> [CMake]   GTest NOT found.  Set ASYNC_SIMPLE_ENABLE_TESTS OFF to skip tests.
1> [CMake] 
1> [CMake] 
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "G:/git/async_simple/out/build/x64-Debug/CMakeFiles/CMakeOutput.log".
1> [CMake] See also "G:/git/async_simple/out/build/x64-Debug/CMakeFiles/CMakeError.log".
1> “C:\Windows\system32\cmd.exe”“/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "d:\vs2022\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="G:\git\async_simple\out\install\x64-Debug" -DCMAKE_C_COMPILER:FILEPATH="D:/vs2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="D:/vs2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="d:\vs2022\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "G:\git\async_simple" 2>&1"”执行失败，出现错误:““C:\Windows\system32\cmd.exe”“/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "d:\vs2022\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="G:\git\async_simple\out\install\x64-Debug" -DCMAKE_C_COMPILER:FILEPATH="D:/vs2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="D:/vs2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="d:\vs2022\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "G:\git\async_simple" 2>&1"”已返回，并带有退出代码: 1”。
`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
It looks like you didn't install gtest. It is necessary to build it. If you don't want to install gtest after, you could specify `-DASYNC_SIMPLE_ENABLE_TESTS=OFF` option as the doc said. But it is highly suggested to install the gtest.

**Comment by ChuanqiXu9** [comment]
> So, would you consider whether to add third-party libraries to the project？

Currently it is not planned. I suggest that you could build it from the source. It is described in the README and it wouldn't be too hard.

**Comment by poor-circle** [comment]
> 

Maybe you can use vcpkg to install gtest? It's a nice choice for windows c++ developer.

**Comment by poor-circle** [comment]
> So, would you consider whether to add third-party libraries to the project？

May you can use vcpkg to install gtest? It's a good choice to build dependencies from source.

(async_simple can work without libaio)

**Comment by poor-circle** [comment]
> So, would you consider whether to add third-party libraries to the project？

May you can use vcpkg to install gtest? It's a good choice to build dependencies from source.

(async_simple can work without libaio)

**Comment by poor-circle** [comment]
By the way, maybe we can add some info about build async_simple in Windows at README.

**Comment by ChuanqiXu9** [comment]
> By the way, maybe we can add some info about build async_simple in Windows at README.

Good idea. You can work on that or file a new issue.

**Comment by 4kangjc** [comment]
after https://github.com/alibaba/async_simple/pull/180, you can use bazel on windows, for example, `bazel build  --config=windows :aysnc_simple`, bazel will pull third-party libraries

**Comment by nqf** [comment]
https://github.com/alibaba/async_simple/issues/202  It should be possible to automatically download gtest

**Comment by fantasy-peak** [comment]
> Oh yes. @4kangjc @nqf could you verify this? If yes, the issue can be closed.

I didn't verify it.，Because I don't have a win development environment

**Comment by 4kangjc** [comment]
> Oh yes. @4kangjc @nqf could you verify this? If yes, the issue can be closed.

Update Windows CI with cmake

**Comment by 4kangjc** [comment]
> ```
> $ cmake ..
> -- Building for: Visual Studio 17 2022
> -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19043.
> -- The CXX compiler identification is MSVC 19.34.31933.0
> -- The C compiler identification is MSVC 19.34.31933.0
> -- The ASM compiler identification is MSVC
> -- Found assembler: D:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: d:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: d:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- CMAKE_MODULE_PATH: C:/Users/nqf/Desktop/async_simple/cmake
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - not found
> -- Found Threads: TRUE
> -- FindAio.cmake:
> CMake Warning (dev) at D:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
>   The package name passed to `find_package_handle_standard_args` (aio) does
>   not match the name of the calling package (Aio).  This can lead to problems
>   in calling code that expects `find_package` result variables (e.g.,
>   `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
>   cmake/FindAio.cmake:22 (find_package_handle_standard_args)
>   CMakeLists.txt:18 (find_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Could NOT find aio (missing: LIBAIO_LIBRARIES)
> CMake Warning (dev) at D:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
>   The package name passed to `find_package_handle_standard_args` (benchmark)
>   does not match the name of the calling package (Benchmark).  This can lead
>   to problems in calling code that expects `find_package` result variables
>   (e.g., `_FOUND`) to follow a certain pattern.
> Call Stack (most recent call first):
>   cmake/FindBenchmark.cmake:25 (find_package_handle_standard_args)
>   CMakeLists.txt:20 (find_package)
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> -- Could NOT find benchmark (missing: BENCHMARK_LIBRARIES BENCHMARK_INCLUDE_DIR)
> -- fetch GTest from https://github.com/google/googletest.git
> -- Found Python: E:/Program Files/Python39/python.exe (found version "3.9.4") found components: Interpreter
> -- GTest: C:/Users/nqf/Desktop/async_simple/build/_deps/googletest-src/googletest/include/, gtest_main
> -- Gmock: C:/Users/nqf/Desktop/async_simple/build/_deps/googletest-src/googlemock/include/, gmock_main
> -- Skipping benchmarks
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/Users/nqf/Desktop/async_simple/build
> 
> -------------------------------------------------------------------------------------
> PS C:\Users\fantasy-peak\Desktop\async_simple\build> MSBuild.exe .\async_simple.sln
> MSBuild version 17.4.0+18d5aef85 for .NET Framework
> 在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
> 生成启动时间为 2022/11/9 21:51:32。
> 节点 1 上的项目“C:\Users\fantasy-peak\Desktop\async_simple\build\async_simple.sln”(默认目标)。
> ValidateSolutionConfiguration:
>   正在生成解决方案配置“Debug|x64”。
> ValidateProjects:
>   在解决方案配置“Debug|x64”中未选定生成项目“INSTALL”。
>   在解决方案配置“Debug|x64”中未选定生成项目“RUN_TESTS”。
> 项目“C:\Users\fantasy-peak\Desktop\async_simple\build\async_simple.sln”(1)正在节点 1 上生成“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj.metaproj”(2) (默认目标)。
> 项目“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj.metaproj”(2)正在节点 1 上生成“C:\Users\fantasy-peak\Desktop\async_simple\build\demo_example\CountChar.vcxproj.metaproj”(3) (默认目标)。
> 项目“C:\Users\fantasy-peak\Desktop\async_simple\build\demo_example\CountChar.vcxproj.metaproj”(3)正在节点 1 上生成“C:\Users\fantasy-peak\Desktop\async_simple\build\ZERO_CHECK.vcxproj”(4) (默认目标)。
> InitializeBuildStatus:
>   正在创建“x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
> CustomBuild:
>   所有输出均为最新。
> .....
> 项目“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj.metaproj”(2)正在节点 1 上生成“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj”(44) (默认目标)。
> PrepareForBuild:
>   正在创建目录“x64\Debug\ALL_BUILD\”。
>   正在创建目录“x64\Debug\ALL_BUILD\ALL_BUILD.tlog\”。
> InitializeBuildStatus:
>   正在创建“x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
> CustomBuild:
>   Building Custom Rule C:/Users/fantasy-peak/Desktop/async_simple/CMakeLists.txt
> FinalizeBuildStatus:
>   正在删除文件“x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild”。
>   正在对“x64\Debug\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate”执行 Touch 任务。
> 已完成生成项目“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj”(默认目标)的操作。
> 
> 已完成生成项目“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj.metaproj”(默认目标)的操作。
> 
> 已完成生成项目“C:\Users\fantasy-peak\Desktop\async_simple\build\async_simple.sln”(默认目标)的操作。
> 
> 
> 已成功生成。
>     0 个警告
>     0 个错误
> 
> 已用时间 00:01:40.83
> ```

可以在CI里加一下ctest

**Comment by fantasy-peak** [comment]
> > ```
> > $ cmake ..
> > -- Building for: Visual Studio 17 2022
> > -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19043.
> > -- The CXX compiler identification is MSVC 19.34.31933.0
> > -- The C compiler identification is MSVC 19.34.31933.0
> > -- The ASM compiler identification is MSVC
> > -- Found assembler: D:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe
> > -- Detecting CXX compiler ABI info
> > -- Detecting CXX compiler ABI info - done
> > -- Check for working CXX compiler: d:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
> > -- Detecting CXX compile features
> > -- Detecting CXX compile features - done
> > -- Detecting C compiler ABI info
> > -- Detecting C compiler ABI info - done
> > -- Check for working C compiler: d:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
> > -- Detecting C compile features
> > -- Detecting C compile features - done
> > -- CMAKE_MODULE_PATH: C:/Users/nqf/Desktop/async_simple/cmake
> > -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> > -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> > -- Looking for pthread_create in pthreads
> > -- Looking for pthread_create in pthreads - not found
> > -- Looking for pthread_create in pthread
> > -- Looking for pthread_create in pthread - not found
> > -- Found Threads: TRUE
> > -- FindAio.cmake:
> > CMake Warning (dev) at D:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
> >   The package name passed to `find_package_handle_standard_args` (aio) does
> >   not match the name of the calling package (Aio).  This can lead to problems
> >   in calling code that expects `find_package` result variables (e.g.,
> >   `_FOUND`) to follow a certain pattern.
> > Call Stack (most recent call first):
> >   cmake/FindAio.cmake:22 (find_package_handle_standard_args)
> >   CMakeLists.txt:18 (find_package)
> > This warning is for project developers.  Use -Wno-dev to suppress it.
> > 
> > -- Could NOT find aio (missing: LIBAIO_LIBRARIES)
> > CMake Warning (dev) at D:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
> >   The package name passed to `find_package_handle_standard_args` (benchmark)
> >   does not match the name of the calling package (Benchmark).  This can lead
> >   to problems in calling code that expects `find_package` result variables
> >   (e.g., `_FOUND`) to follow a certain pattern.
> > Call Stack (most recent call first):
> >   cmake/FindBenchmark.cmake:25 (find_package_handle_standard_args)
> >   CMakeLists.txt:20 (find_package)
> > This warning is for project developers.  Use -Wno-dev to suppress it.
> > 
> > -- Could NOT find benchmark (missing: BENCHMARK_LIBRARIES BENCHMARK_INCLUDE_DIR)
> > -- fetch GTest from https://github.com/google/googletest.git
> > -- Found Python: E:/Program Files/Python39/python.exe (found version "3.9.4") found components: Interpreter
> > -- GTest: C:/Users/nqf/Desktop/async_simple/build/_deps/googletest-src/googletest/include/, gtest_main
> > -- Gmock: C:/Users/nqf/Desktop/async_simple/build/_deps/googletest-src/googlemock/include/, gmock_main
> > -- Skipping benchmarks
> > -- Configuring done
> > -- Generating done
> > -- Build files have been written to: C:/Users/nqf/Desktop/async_simple/build
> > 
> > -------------------------------------------------------------------------------------
> > PS C:\Users\fantasy-peak\Desktop\async_simple\build> MSBuild.exe .\async_simple.sln
> > MSBuild version 17.4.0+18d5aef85 for .NET Framework
> > 在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
> > 生成启动时间为 2022/11/9 21:51:32。
> > 节点 1 上的项目“C:\Users\fantasy-peak\Desktop\async_simple\build\async_simple.sln”(默认目标)。
> > ValidateSolutionConfiguration:
> >   正在生成解决方案配置“Debug|x64”。
> > ValidateProjects:
> >   在解决方案配置“Debug|x64”中未选定生成项目“INSTALL”。
> >   在解决方案配置“Debug|x64”中未选定生成项目“RUN_TESTS”。
> > 项目“C:\Users\fantasy-peak\Desktop\async_simple\build\async_simple.sln”(1)正在节点 1 上生成“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj.metaproj”(2) (默认目标)。
> > 项目“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj.metaproj”(2)正在节点 1 上生成“C:\Users\fantasy-peak\Desktop\async_simple\build\demo_example\CountChar.vcxproj.metaproj”(3) (默认目标)。
> > 项目“C:\Users\fantasy-peak\Desktop\async_simple\build\demo_example\CountChar.vcxproj.metaproj”(3)正在节点 1 上生成“C:\Users\fantasy-peak\Desktop\async_simple\build\ZERO_CHECK.vcxproj”(4) (默认目标)。
> > InitializeBuildStatus:
> >   正在创建“x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
> > CustomBuild:
> >   所有输出均为最新。
> > .....
> > 项目“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj.metaproj”(2)正在节点 1 上生成“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj”(44) (默认目标)。
> > PrepareForBuild:
> >   正在创建目录“x64\Debug\ALL_BUILD\”。
> >   正在创建目录“x64\Debug\ALL_BUILD\ALL_BUILD.tlog\”。
> > InitializeBuildStatus:
> >   正在创建“x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
> > CustomBuild:
> >   Building Custom Rule C:/Users/fantasy-peak/Desktop/async_simple/CMakeLists.txt
> > FinalizeBuildStatus:
> >   正在删除文件“x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild”。
> >   正在对“x64\Debug\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate”执行 Touch 任务。
> > 已完成生成项目“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj”(默认目标)的操作。
> > 
> > 已完成生成项目“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj.metaproj”(默认目标)的操作。
> > 
> > 已完成生成项目“C:\Users\fantasy-peak\Desktop\async_simple\build\async_simple.sln”(默认目标)的操作。
> > 
> > 
> > 已成功生成。
> >     0 个警告
> >     0 个错误
> > 
> > 已用时间 00:01:40.83
> > ```
> 
> 可以在CI里加一下ctest，把`DASYNC_SIMPLE_ENABLE_TESTS`打开

run: cmake --build Build/${{ matrix   在这个位置加对吧？

**Comment by 4kangjc** [comment]
> > > ```
> > > $ cmake ..
> > > -- Building for: Visual Studio 17 2022
> > > -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19043.
> > > -- The CXX compiler identification is MSVC 19.34.31933.0
> > > -- The C compiler identification is MSVC 19.34.31933.0
> > > -- The ASM compiler identification is MSVC
> > > -- Found assembler: D:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe
> > > -- Detecting CXX compiler ABI info
> > > -- Detecting CXX compiler ABI info - done
> > > -- Check for working CXX compiler: d:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
> > > -- Detecting CXX compile features
> > > -- Detecting CXX compile features - done
> > > -- Detecting C compiler ABI info
> > > -- Detecting C compiler ABI info - done
> > > -- Check for working C compiler: d:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
> > > -- Detecting C compile features
> > > -- Detecting C compile features - done
> > > -- CMAKE_MODULE_PATH: C:/Users/nqf/Desktop/async_simple/cmake
> > > -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> > > -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> > > -- Looking for pthread_create in pthreads
> > > -- Looking for pthread_create in pthreads - not found
> > > -- Looking for pthread_create in pthread
> > > -- Looking for pthread_create in pthread - not found
> > > -- Found Threads: TRUE
> > > -- FindAio.cmake:
> > > CMake Warning (dev) at D:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
> > >   The package name passed to `find_package_handle_standard_args` (aio) does
> > >   not match the name of the calling package (Aio).  This can lead to problems
> > >   in calling code that expects `find_package` result variables (e.g.,
> > >   `_FOUND`) to follow a certain pattern.
> > > Call Stack (most recent call first):
> > >   cmake/FindAio.cmake:22 (find_package_handle_standard_args)
> > >   CMakeLists.txt:18 (find_package)
> > > This warning is for project developers.  Use -Wno-dev to suppress it.
> > > 
> > > -- Could NOT find aio (missing: LIBAIO_LIBRARIES)
> > > CMake Warning (dev) at D:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
> > >   The package name passed to `find_package_handle_standard_args` (benchmark)
> > >   does not match the name of the calling package (Benchmark).  This can lead
> > >   to problems in calling code that expects `find_package` result variables
> > >   (e.g., `_FOUND`) to follow a certain pattern.
> > > Call Stack (most recent call first):
> > >   cmake/FindBenchmark.cmake:25 (find_package_handle_standard_args)
> > >   CMakeLists.txt:20 (find_package)
> > > This warning is for project developers.  Use -Wno-dev to suppress it.
> > > 
> > > -- Could NOT find benchmark (missing: BENCHMARK_LIBRARIES BENCHMARK_INCLUDE_DIR)
> > > -- fetch GTest from https://github.com/google/googletest.git
> > > -- Found Python: E:/Program Files/Python39/python.exe (found version "3.9.4") found components: Interpreter
> > > -- GTest: C:/Users/nqf/Desktop/async_simple/build/_deps/googletest-src/googletest/include/, gtest_main
> > > -- Gmock: C:/Users/nqf/Desktop/async_simple/build/_deps/googletest-src/googlemock/include/, gmock_main
> > > -- Skipping benchmarks
> > > -- Configuring done
> > > -- Generating done
> > > -- Build files have been written to: C:/Users/nqf/Desktop/async_simple/build
> > > 
> > > -------------------------------------------------------------------------------------
> > > PS C:\Users\fantasy-peak\Desktop\async_simple\build> MSBuild.exe .\async_simple.sln
> > > MSBuild version 17.4.0+18d5aef85 for .NET Framework
> > > 在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
> > > 生成启动时间为 2022/11/9 21:51:32。
> > > 节点 1 上的项目“C:\Users\fantasy-peak\Desktop\async_simple\build\async_simple.sln”(默认目标)。
> > > ValidateSolutionConfiguration:
> > >   正在生成解决方案配置“Debug|x64”。
> > > ValidateProjects:
> > >   在解决方案配置“Debug|x64”中未选定生成项目“INSTALL”。
> > >   在解决方案配置“Debug|x64”中未选定生成项目“RUN_TESTS”。
> > > 项目“C:\Users\fantasy-peak\Desktop\async_simple\build\async_simple.sln”(1)正在节点 1 上生成“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj.metaproj”(2) (默认目标)。
> > > 项目“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj.metaproj”(2)正在节点 1 上生成“C:\Users\fantasy-peak\Desktop\async_simple\build\demo_example\CountChar.vcxproj.metaproj”(3) (默认目标)。
> > > 项目“C:\Users\fantasy-peak\Desktop\async_simple\build\demo_example\CountChar.vcxproj.metaproj”(3)正在节点 1 上生成“C:\Users\fantasy-peak\Desktop\async_simple\build\ZERO_CHECK.vcxproj”(4) (默认目标)。
> > > InitializeBuildStatus:
> > >   正在创建“x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
> > > CustomBuild:
> > >   所有输出均为最新。
> > > .....
> > > 项目“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj.metaproj”(2)正在节点 1 上生成“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj”(44) (默认目标)。
> > > PrepareForBuild:
> > >   正在创建目录“x64\Debug\ALL_BUILD\”。
> > >   正在创建目录“x64\Debug\ALL_BUILD\ALL_BUILD.tlog\”。
> > > InitializeBuildStatus:
> > >   正在创建“x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild”，因为已指定“AlwaysCreate”。
> > > CustomBuild:
> > >   Building Custom Rule C:/Users/fantasy-peak/Desktop/async_simple/CMakeLists.txt
> > > FinalizeBuildStatus:
> > >   正在删除文件“x64\Debug\ALL_BUILD\ALL_BUILD.tlog\unsuccessfulbuild”。
> > >   正在对“x64\Debug\ALL_BUILD\ALL_BUILD.tlog\ALL_BUILD.lastbuildstate”执行 Touch 任务。
> > > 已完成生成项目“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj”(默认目标)的操作。
> > > 
> > > 已完成生成项目“C:\Users\fantasy-peak\Desktop\async_simple\build\ALL_BUILD.vcxproj.metaproj”(默认目标)的操作。
> > > 
> > > 已完成生成项目“C:\Users\fantasy-peak\Desktop\async_simple\build\async_simple.sln”(默认目标)的操作。
> > > 
> > > 
> > > 已成功生成。
> > >     0 个警告
> > >     0 个错误
> > > 
> > > 已用时间 00:01:40.83
> > > ```
> > 
> > 
> > 可以在CI里加一下ctest，把`DASYNC_SIMPLE_ENABLE_TESTS`打开
> 
> 在这个位置加对吧？https://github.com/alibaba/async_simple/blob/main/.github/workflows/windows.yml#L30-L30

嗯，可以参考一下其他平台

**Comment by ChuanqiXu9** [comment]
This one should be closed with https://github.com/alibaba/async_simple/pull/208
