### ISSUE TITLE
使用gcc11编译报错

### ISSUE THREAD

**Issue by morebtcg** [alibaba/async_simple#144]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
在Ubuntu 22.04系统上，执行cmake步骤成功，make步骤报错
make时报跟gtest相关的错误，推断是新版编译器检查变严格了

### Reproduction way
首先安装依赖库，再用vcpkg安装gtest

进入async-simple目录，执行
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE=/home/more/vcpkg/scripts/buildsystems/vcpkg.cmake ../
make

报错如下：
![图片](https://user-images.githubusercontent.com/12828840/189842196-bc88b695-6882-403f-99f8-e36f3fcd529a.png)

async_simple版本是ffe22759167749f7b3adb8d3359af6bc398bb4f7
vcpkg版本是8eb76645c009c2a2e778e03bcbfb9b5e1be3aa40
gtest版本是1.12.0，da295db55242fd454a3b42486c3f9043356ca40f

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
推荐的解决方案是使用 v1.8 版本的 gtest，或者开启 Wno-sign-compare (相对不推荐)

**Comment by morebtcg** [comment]
#146 修改代码可以通过编译

**Comment by ChuanqiXu9** [comment]
> #146 修改代码可以通过编译

oh，确实是我看漏了，非常抱歉

**Comment by ChuanqiXu9** [comment]
This one should be closed.
