### ISSUE TITLE
建议使用std::variant保存LazyPromise的成员变量

### ISSUE THREAD

**Issue by morebtcg** [alibaba/async_simple#150]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

在以下源码中
[Lazy.h](https://github.com/alibaba/async_simple/blob/main/async_simple/coro/Lazy.h)

LazyPromise的成员变量描述如下：
```
enum class result_type { empty, value, exception };
result_type _resultType = result_type::empty;
union {
    T _value;
    std::exception_ptr _exception;
};
```

LazyPromise通过这几个成员变量和LazyPromise的构造、析构函数，实现了类似variant的逻辑。

此处直接使用std::variant是不是更好？只需一行代码就可以实现前述功能：

`std::variant<std::monostate, T, std::exception_ptr>`

### Are you willing to submit a PR?

- [x] #151

**Comment by morebtcg** [comment]
#157

**Comment by ChuanqiXu9** [comment]
交 PR 时可以设置和 Issue 自动关联的
