### ISSUE TITLE
CMakeLists.txt 脚本应避免硬编码调试选项

### ISSUE THREAD

**Issue by yanminhui** [alibaba/async_simple#156]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

```.cmake
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Release")
endif()

# set CXXFALGS
if(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
    set(CXX_FLAGS
        /std:c++20
        /await:strict
        /EHa
        )
else()
    set(CXX_FLAGS
        -std=c++20
        -D_GLIBCXX_USE_CXX11_ABI=1
        -Wno-deprecated-register
        -D_FILE_OFFSET_BITS=64
        -fPIC
        -Wall
        -Werror
        -D__STDC_LIMIT_MACROS
        -g
        )
endif()
```

如上，CMakeLists.txt 直接将编译参数硬编码，这使得 `CMAKE_BUILD_TYPE` 无法决定是否生成调试信息 `-g` 。

现在这样写与单元测试行为冲突，如 `testLazyPerf`，通过 `NDEBUG` 检测是否有生成调试信息设置不同参数，实际上无论 `NDEBUG` 是什么，其实都设置了 `-g`，代码与期望不一致。

```.cpp
TEST_F(LazyTest, testLazyPerf) {
    // The code compiled by GCC with Debug would fail
    // if test_loop is 5000.
#ifndef NDEBUG
    auto test_loop = 50;
    auto expected_sum = 23250;
#else 
    auto test_loop = 5000;
    auto expected_sum = 2325000;
#endif

    auto total = 0;

    auto one = [](int n) -> Lazy<int> {
        auto x = n;
        co_return x;
    };
    // ...
}
```

### Anything else

由 #154 94b2f39 发现该问题。 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
NDEBUG 和 `-g` 并不是绑定的。在 Release 模式下生成 Debug 信息还挺普遍的。

**Comment by yanminhui** [comment]
> NDEBUG 和 `-g` 并不是绑定的。在 Release 模式下生成 Debug 信息还挺普遍的。

CMake 的 `CMAKE_BUILD_TYPE=RelWithDebInfo` 支持带上 `NDEBUG` 和 `-g`，一般情况由 `CMAKE_BUILD_TYPE` 来控制，不应覆盖默认行为。

另，虽 `NDEBUG` 和 `-g` 不是强绑定的，但一般情况它们俩都在一起的，如上述的 UT 作者应该就是这么认为的。

**Comment by ChuanqiXu9** [comment]
> > NDEBUG 和 `-g` 并不是绑定的。在 Release 模式下生成 Debug 信息还挺普遍的。
> 
> CMake 的 `CMAKE_BUILD_TYPE=RelWithDebInfo` 支持带上 `NDEBUG` 和 `-g`，一般情况由 `CMAKE_BUILD_TYPE` 来控制，不应覆盖默认行为。
> 

这个是 CMake 的默认推荐而已。我们实践中一般用 `NDEBUG` 检测是否处于 Debug 状态，用于编写只在 Debug 下运行的代码，但 `-g` 是普遍都会使用的。

> 另，虽 `NDEBUG` 和 `-g` 不是强绑定的，但一般情况它们俩都在一起的，如上述的 UT 作者应该就是这么认为的。

上面的 UT 和  `-g` 没有关系的，可能是注释误导了，这里混淆了 -O0 和 Debug 两个模式。

**Comment by yanminhui** [comment]
> 我们实践中一般用 NDEBUG 检测是否处于 Debug 状态，用于编写只在 Debug 下运行的代码，但 -g 是普遍都会使用的。

一般遵行 CMake 的设计，如果用户既想定义 `NDEBUG` （即处于 `assert` **无效**状态），又想要调试信息，使用 `-DCMAKE_BUILD_TYPE=RelWithDebInfo` 就行了。通过情况下，我们使用 `RelWithDebInfo` 构造类型。

而开发调试时，指定 `-DCMAKE_BUILD_TYPE=Debug`，这个时候不会定义 `NDEBUG`（即处于 `assert` **生效**状态），且有调试信息。

`Debug` 与 `RelWithDebInfo` 符合我们通常的实践，通常不应在脚本内指定这些选项。

**Comment by ChuanqiXu9** [comment]
> > 我们实践中一般用 NDEBUG 检测是否处于 Debug 状态，用于编写只在 Debug 下运行的代码，但 -g 是普遍都会使用的。
> 
> 一般遵行 CMake 的设计，如果用户既想定义 `NDEBUG` （即处于 `assert` **无效**状态），又想要调试信息，使用 `-DCMAKE_BUILD_TYPE=RelWithDebInfo` 就行了。通常情况下，我们使用 `RelWithDebInfo` 构造类型。
> 
> 而开发调试时，指定 `-DCMAKE_BUILD_TYPE=Debug`，这个时候不会定义 `NDEBUG`（即处于 `assert` **生效**状态），且有调试信息。
> 
> `Debug` 与 `RelWithDebInfo` 符合我们通常的实践，通常不应在脚本内指定这些选项。

但这个库基本是头文件的，对于用户使用的选项是无法约束的，实际上这里的选项只是给测试用的而已，让模式简单些会比较好。

另外实践是多种多样的，我们确实会在 Release 模式下（即不开 NDEBUG）使用 -g 选项，这是由我们的业务模式决定的。

**Comment by yanminhui** [comment]
> 另外实践是多种多样的，我们确实会在 Release 模式下（即不开 NDEBUG）使用 -g 选项，这是由我们的业务模式决定的。

你说的这个其实是 `Debug`，如下使用了 `-g`，没有定义 `NDEBUG` (即不开 NDEBUG)。
> //Flags used by the CXX compiler during DEBUG builds.
> CMAKE_CXX_FLAGS_DEBUG:STRING=-g

**Comment by ChuanqiXu9** [comment]
> > 另外实践是多种多样的，我们确实会在 Release 模式下（即不开 NDEBUG）使用 -g 选项，这是由我们的业务模式决定的。
> 
> 你说的这个其实是 `Debug`，如下使用了 `-g`，没有定义 `NDEBUG` (即不开 NDEBUG)。
> 
> > //Flags used by the CXX compiler during DEBUG builds.
> > CMAKE_CXX_FLAGS_DEBUG:STRING=-g

Yeah, typo. 我指 `NDEBUG -O3 -g` 这样的用法。总得来说，在我们的测试里只区分 Debug （不开 NDEBUG、O0、Sanitizer） 以及 Release （O2）两种模式，两种模式下都会生成 `-g` 选项。另外由于代码基本都在头文件里，这些选择对用户也不会有影响。
