### ISSUE TITLE
Compile failure on ubuntu22.04 gcc11

### ISSUE THREAD

**Issue by morebtcg** [alibaba/async_simple#158]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

Using:
ubuntu 22.04
gcc11
72acde7cde680118e0b3b3a8cf72bc4f6d0f63a5

```
cmake ..
make
```

Got
```
c++: error: unrecognized command-line option ‘-fsanitize-address-use-after-return=never’; did you mean ‘-fsanitize-address-use-after-scope’?
```

Due to #149 fefe80f04a700d00e53d62231545c80cba3f4f2b?

![图片](https://user-images.githubusercontent.com/12828840/190951797-4ad43913-8a78-44f0-8acb-1000b6d48644.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
My bad. Thanks for reporting!

**Comment by ChuanqiXu9** [comment]
Close accidently.
