### ISSUE TITLE
支持透传 awaiter

### ISSUE THREAD

**Issue by yanminhui** [alibaba/async_simple#159]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

```.cpp
// This collectAll function can be used to co_await on some different kinds of
// LazyType tasks in one thread,and producing a tuple of Try values containing
// each of the results.
template <template <typename> typename LazyType, typename... Ts>
// The temporary object's life-time which binding to reference(inputs) won't
// be extended to next time of coroutine resume. Just Copy inputs to avoid
// crash.
inline auto collectAll(LazyType<Ts>... inputs) -> Lazy<std::tuple<Try<Ts>...>> {
    if constexpr (0 == sizeof...(Ts)) {
        co_return std::tuple<>{};
    } else {
        co_return co_await detail::collectAllVariadicImpl<false>(
            std::make_index_sequence<sizeof...(Ts)>{}, std::move(inputs)...);
    }
}
```

如上，`collectAll` 的作用只是想将 `collectAllVariadicImpl` 传递出去而已，应支持使用普通函数将其透传给调用者。

```.cpp
template <template <typename> typename LazyType, typename... Ts>
inline auto collectAll(LazyType<Ts>... inputs) -> Lazy<std::tuple<Try<Ts>...>> {
    return detail::collectAllVariadicImpl<false>(
        std::make_index_sequence<sizeof...(Ts)>{}, std::move(inputs)...);
}
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
Good idea。

我感觉可以通过以下这种方式重构下，不过我还没来得及验证

```
template <LazyConcept... LazyType>
inline auto collectAll(LazyTy&&... inputs)  {
     ...
    return detail::collectAllVariadicImpl<false>(
        std::make_index_sequence<sizeof...(Ts)>{}, std::move(inputs)...);
}
```

**Comment by ChuanqiXu9** [comment]
See https://github.com/alibaba/async_simple/issues/160 for related discussion.

**Comment by RainMark** [comment]
没太理解是什么意思，能举个例子吗？

**Comment by ChuanqiXu9** [comment]
> 没太理解是什么意思，能举个例子吗？

在我的角度来看，起码可以在调用链上少一个 Lazy 协程。原理上应该也没有问题，`return 右值` 会触发 guaranteed return value optimization，直接在返回值处构造 Lazy。感觉挺好的，他这个代码有问题只是因为普通函数结尾会析构参数，因为现在这个参数是值类型的。（当然在 collectAll 是协程的情况下，这个代码没有问题，编译器会帮助管理生命周期）

**Comment by RainMark** [comment]
懂了，看了半天没看出区别，原来是少了co await。应该是 co_return return detail::collectAllVariadicImpl吧。collectall协程已经co_return返回了不会析构掉这个frame么？

**Comment by ChuanqiXu9** [comment]
> 懂了，看了半天没看出区别，原来是少了co await。应该是 co_return detail::collectAllVariadicImpl吧。collectall协程已经co_return返回了不会析构掉这个frame么？

不，应该是 `return detail::collectAllVariadicImpl`, 这样写的话 collectAll 就不是协程了，也就没有协程生命周期的问题了。

**Comment by RainMark** [comment]
> > 懂了，看了半天没看出区别，原来是少了co await。应该是 co_return detail::collectAllVariadicImpl吧。collectall协程已经co_return返回了不会析构掉这个frame么？
> 
> 不，应该是 `return detail::collectAllVariadicImpl`, 这样写的话 collectAll 就不是协程了，也就没有协程生命周期的问题了。

如果是return的话，参数不能是值类型吧？

**Comment by ChuanqiXu9** [comment]
> 

对，参数得改成万能引用

**Comment by RainMark** [comment]
> > 
> 
> 对，参数得改成万能引用

这样会和#127冲突吗？貌似不会？因为collectAll不是协程了，如果传给collectAll的是个纯右值的话，collectAllVariadicImpl里面已经move走了。

**Comment by ChuanqiXu9** [comment]
> #127

是的，Impl 的参数得改成值类型，这样才能 move 进去，不然 initial_suspend 后临时变量就释放了
