### ISSUE TITLE
RescheduleLazy should be only allowed in DetachedCoroutine

### ISSUE THREAD

**Issue by ChuanqiXu9** [alibaba/async_simple#163]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

By the design, the `RescheduleLazy ` should be only launched by `RescheduleLazy ::start` method, which will co_await the `RescheduleLazy` itself in a DetachedCoroutine. However, currently we can co_await a` RescheduleLazy` actually like the discussion mentions https://github.com/alibaba/async_simple/discussions/162:

```C++
SimpleExecutor e;

Lazy<void> bar() {}

Lazy<void> foo() {
    co_await bar.via(&e); // Not allowed
}
```

This is confusing. We need to ban such uses explicitly.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by 4kangjc** [comment]
https://github.com/alibaba/async_simple/blob/aa1d71804778f5d1dda71f628dd4e40725ae42ea/async_simple/coro/test/LazyTest.cpp#L359
