### ISSUE TITLE
前向转发可调用对象不应被多次调用

### ISSUE THREAD

**Issue by yanminhui** [alibaba/async_simple#168]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

```.cpp
// It is not travial to implement an asynchronous do_for_each.
template <Range RangeTy, typename Callable>
Future<Unit> do_for_each(RangeTy &&Range, Callable &&func) {
    auto Begin = Range.begin();
    auto End = Range.end();

    if (Begin == End)
        return makeReadyFuture(Unit());

    while (true) {
        auto F = std::invoke(func, *(Begin++));
        // If we met an error, return early.
        if (F.result().hasError() || Begin == End)
            return F;

        if (!F.hasResult())
            return std::move(F).thenTry(
                [func = std::forward<Callable>(func), Begin = std::move(Begin),
                 End = std::move(End)](auto &&) mutable {
                    return do_for_each(SubRange(Begin, End),
                                       std::forward<Callable>(func));
                });
    }
}
```

如上，`func` 为 [`forwarding references`](https://en.cppreference.com/w/cpp/language/reference)，一般在应用处应用 `std::forward` 进行转换以使 `func` 保持右值属性，否则无论如何它将是一个左值，达不到对于右值使用移动操作的目的。

若将其加上，改为 `std::invoke(std::forward<Callable>(func), *(Begin++))` ，在 `while` 内被调用多次，可能引发副作用，见 [How do correctly use a callable passed through forwarding reference?](https://stackoverflow.com/questions/55786775/how-do-correctly-use-a-callable-passed-through-forwarding-reference)

按照 C++ 一般惯用法，对于需要被调用多次的谓词，应拷贝其对象，如 STL 算法库对于带谓词的操作均声明为拷贝语义。

```.cpp
template <Range RangeTy, typename Callable>
Future<Unit> do_for_each(RangeTy &&Range, Callable func) {
    auto Rng = std::forward<RangeTy>(Range);
    auto Begin = Rng.begin();
    auto End = Rng.end();
    // ...
}
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
std::invoke 这里不加上 forward 也没什么问题的，调用本身只会引用，不会触法构造。另外这是个表示异步操作API不好实现的例子，比较复杂也挺正常的。

**Comment by RainMark** [comment]
这里只是引用的话，直接申明为 Callable& func 是不是更好？

**Comment by ChuanqiXu9** [comment]
> 

这里 invoke 没有重载的问题，我觉得不必以形害意。不过你更倾向于这种风格的话，也可以提个 PR。

**Comment by RainMark** [comment]
这里因为invoke不会存储lambda，有别于stl容器。所以我理解 @ChuanqiXu9 的意思是加不加forward都可以

**Comment by yanminhui** [comment]
> 这里因为invoke不会存储lambda，有别于stl容器。所以我理解 @ChuanqiXu9 的意思是加不加forward都可以

[std::copy_if](https://en.cppreference.com/w/cpp/algorithm/copy) 也是不会存储可调用对象，可能实现如下：

```.cpp
template<class InputIt, class OutputIt, class UnaryPredicate>
OutputIt copy_if(InputIt first, InputIt last, 
                 OutputIt d_first, UnaryPredicate pred)
{
    for (; first != last; ++first) {
        if (pred(*first)) {
            *d_first = *first;
            ++d_first;
        }
    }
    return d_first;
}
```

不加 `std::forward<Callable>()`，`func`（永远是个左值） 在 `while` 循环中同一个对象被调用多次，是没有问题，但这 **与声明的语义可能就不那么一致，forwarding reference 意味着对于右值可能被移走，但这里永远都不会。** 其次，这对调用者来说意味如果 `func` 是个右值，理论上应该调用 `T &&operator()() &&` 重载，而不是一直调用 `const T &operator()() const &`，但目前的实现会一直调用后者而忽略前者。 C++ 惯用法，一般是 forwarding reference 与 `std::forward` 成对出现。

若加上 `std::forward<Callable>`，`func`（可能是个右值） 在 `while` 循环中同一个对象被调用多次，可能产生的副作用可以看 [How do correctly use a callable passed through forwarding reference?](https://stackoverflow.com/questions/55786775/how-do-correctly-use-a-callable-passed-through-forwarding-reference) 精选的答案：https://stackoverflow.com/a/55787351/19863959

结论是如果声明为 `Callable func`，那么语义是明确的，表示如果实参是右值，永远不会被移走，也不会调用 `&&` 限定的方法。

**Comment by RainMark** [comment]
申明为Callable func的话由于这个case里上层调用do_for_each pass的是纯右值会触发copy elision没啥问题。但是万一上面传的是个左值lambda的话，感觉就引入不必要拷贝了。

**Comment by yanminhui** [comment]
> 申明为Callable func的话由于这个case里上层调用do_for_each pass的是纯右值会触发copy elision没啥问题。但是万一上面传的是个左值lambda的话，感觉就引入不必要拷贝了。

你担心的这个问题，Scott Meyers «[Effective C++](http://aleda.cn/books/Effective_C++.pdf)» 条款20 给出了建议：

It used to be generally recommended best practice to **use pass by const ref for all types, except for builtin types (char, int, double, etc.), for iterators and for function objects** (lambdas, classes deriving from std::*_function). 

浏览一下 STL 算法均如此，如果你认为实参的拷贝是昂贵的，应使用 `std::ref` 包裹它。
