### ISSUE TITLE
Support concept

### ISSUE THREAD

**Issue by 4kangjc** [alibaba/async_simple#172]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
use c++20 concept instead of std::enable_if

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
是的，这应该是个长期的方向，我们之前改过一些，但没有全部一次性改掉；
