### ISSUE TITLE
Support Docker

### ISSUE THREAD

**Issue by 4kangjc** [alibaba/async_simple#175]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
docker support
```Dockerfile
FROM gcc:11

RUN apt -y update && apt install -y gcc g++ cmake libaio-dev libgtest-dev libgmock-dev

```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
我觉得能跑通的话，再加一个文档（说清楚调用的环境）就可以发个 PR 了

**Comment by 4kangjc** [comment]
> 我觉得能跑通的话，再加一个文档（说清楚调用的环境）就可以发个 PR 了

有时间弄一下

**Comment by fantasy-peak** [comment]
> > 我觉得能跑通的话，再加一个文档（说清楚调用的环境）就可以发个 PR 了
> 
> 有时间弄一下

你在整吗，如果你没整，我将先添加一个centos7 的dockerfile

**Comment by 4kangjc** [comment]
> > > 我觉得能跑通的话，再加一个文档（说清楚调用的环境）就可以发个 PR 了
> > 
> > 
> > 有时间弄一下
> 
> 你在整吗，如果你没整，我将先添加一个centos7 的dockerfile

可以你先弄吧

**Comment by 4kangjc** [comment]
> > > > 我觉得能跑通的话，再加一个文档（说清楚调用的环境）就可以发个 PR 了
> > > 
> > > 
> > > 有时间弄一下
> > 
> > 
> > 你在整吗，如果你没整，我将先添加一个centos7 的dockerfile
> 
> 可以你先弄吧

我觉得可以建一个docker的文件夹

**Comment by fantasy-peak** [comment]
> > > > > 我觉得能跑通的话，再加一个文档（说清楚调用的环境）就可以发个 PR 了
> > > > 
> > > > 
> > > > 有时间弄一下
> > > 
> > > 
> > > 你在整吗，如果你没整，我将先添加一个centos7 的dockerfile
> > 
> > 
> > 可以你先弄吧
> 
> 我觉得可以建一个docker的文件夹

好，我就准备创建一个文件夹，里面有centos,ububtu等
