### ISSUE TITLE
Invalid assert

### ISSUE THREAD

**Issue by 4kangjc** [alibaba/async_simple#177]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

##### 背景：
在一台**一核2g**的阿里云服务器上测试`support-bazel`，使用`bazel test ...`时，`async_simple/util/test/async_simple_util_test`出core，`assert`在了https://github.com/alibaba/async_simple/blob/06f321a78992fb76f1f34cd5001c77859d027460/async_simple/util/ThreadPool.h#L188
查看测试代码https://github.com/alibaba/async_simple/blob/06f321a78992fb76f1f34cd5001c77859d027460/async_simple/util/test/ThreadPoolTest.cpp#L81
所以`assert`的原因很简单，`id`和`_threadNum`都是1，所以触发了`assert`，将测试代码改成
```c++
pool.scheduleById([&pool] { EXPECT_EQ(pool.getCurrentId(), 0); }, 0);
```
后通过测试

#### 问题描述：
我用`cmake`编出来的`async_simple/util/test/async_simple_util_test`并没有`assert`，而是程序卡死了，应该是`vector`越界的原因，`assert`判断通过了，查看cmake编译选项发现打开了NDEBUG  
个人认为测试代码默认应该关掉这个？

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
> 我用cmake编出来的async_simple/util/test/async_simple_util_test并没有assert，而是程序卡死了，应该是vector越界的原因，assert判断通过了，查看cmake编译选项发现打开了NDEBUG
个人认为测试代码默认应该关掉这个？

NDEBUG 应该只是在 Release 模式下被定义？我觉得改下也比较合理；

> 所以assert的原因很简单，id和_threadNum都是1，所以触发了assert，将测试代码改成

这个好奇怪，也一直都没有发现；感觉是可以单独发个PR改改

**Comment by 4kangjc** [comment]
> > 我用cmake编出来的async_simple/util/test/async_simple_util_test并没有assert，而是程序卡死了，应该是vector越界的原因，assert判断通过了，查看cmake编译选项发现打开了NDEBUG
> > 个人认为测试代码默认应该关掉这个？
> 
> NDEBUG 应该只是在 Release 模式下被定义？我觉得改下也比较合理；
> 
> > 所以assert的原因很简单，id和_threadNum都是1，所以触发了assert，将测试代码改成
> 
> 这个好奇怪，也一直都没有发现；感觉是可以单独发个PR改改

因为机器是1核两g的，
https://github.com/alibaba/async_simple/blob/06f321a78992fb76f1f34cd5001c77859d027460/async_simple/util/test/ThreadPoolTest.cpp#L94
所以线程池里的线程数只有1

**Comment by ChuanqiXu9** [comment]
> > > 我用cmake编出来的async_simple/util/test/async_simple_util_test并没有assert，而是程序卡死了，应该是vector越界的原因，assert判断通过了，查看cmake编译选项发现打开了NDEBUG
> > > 个人认为测试代码默认应该关掉这个？
> > 
> > 
> > NDEBUG 应该只是在 Release 模式下被定义？我觉得改下也比较合理；
> > > 所以assert的原因很简单，id和_threadNum都是1，所以触发了assert，将测试代码改成
> > 
> > 
> > 这个好奇怪，也一直都没有发现；感觉是可以单独发个PR改改
> 
> 因为机器是1核两g的，
> 
> https://github.com/alibaba/async_simple/blob/06f321a78992fb76f1f34cd5001c77859d027460/async_simple/util/test/ThreadPoolTest.cpp#L94
> 
> 
> 所以线程池里的线程数只有1

明白了，怪不得一直没发现
