### ISSUE TITLE
testCollectAllBatched fails occasionally in https://github.com/alibaba/async_simple/pull/206

### ISSUE THREAD

**Issue by ChuanqiXu9** [alibaba/async_simple#207]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

In a testing for the PR (https://github.com/alibaba/async_simple/pull/206), the `testCollectAllBatched ` fails and PR looks not related to this problem. We need to review the implementation for `testCollectAllBatched ` and try to reproduce it.

**Comment by ChuanqiXu9** [comment]
Weird, I've tried many times with many different compilers (clang11.0.0, clang11.1.0 and clang13) but I still can't reproduce this.

**Comment by 4kangjc** [comment]
最新的一次测试也出现了这个问题，应该与PR (https://github.com/alibaba/async_simple/pull/206)无关

**Comment by ChuanqiXu9** [comment]
> PR 206

是的，和这个明显没关系

**Comment by ChuanqiXu9** [comment]
@4kangjc 你在本地可以复现这个问题吗

**Comment by 4kangjc** [comment]
> @4kangjc 你在本地可以复现这个问题吗

没有复现出来

**Comment by 4kangjc** [comment]
![Screenshot_20221111_184311](https://user-images.githubusercontent.com/73515066/201324048-873a2e07-854b-412b-a33c-d0c7b2042e0e.png)

**Comment by ChuanqiXu9** [comment]
It looks the problem is relatively stable now. Let's close this and reopen it if necessary.
