### ISSUE TITLE
SEGFAULT: run_async_simple_uthread_test

### ISSUE THREAD

**Issue by yanminhui** [alibaba/async_simple#209]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

```.bash
Test project /Users/admin/repos/pr/async_simple/build
    Start 1: run_async_simple_test
1/5 Test #1: run_async_simple_test ............   Passed    2.48 sec
    Start 2: run_async_simple_util_test
2/5 Test #2: run_async_simple_util_test .......   Passed    0.33 sec
    Start 3: run_async_simple_coro_test
3/5 Test #3: run_async_simple_coro_test .......   Passed   18.11 sec
    Start 4: run_async_simple_executor_test
4/5 Test #4: run_async_simple_executor_test ...   Passed    0.34 sec
    Start 5: run_async_simple_uthread_test
5/5 Test #5: run_async_simple_uthread_test ....***Exception: SegFault  0.52 sec

80% tests passed, 1 tests failed out of 5

Total Test time (real) =  21.79 sec

The following tests FAILED:
	  5 - run_async_simple_uthread_test (SEGFAULT)
Errors while running CTest
```

Platform: Apple M2 (macOS 13.0 (22A380))

```.bash
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix
```

### Anything else

It seems caused by #195 and work well if revert #195 (@4kangjc ).

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by 4kangjc** [comment]
看下日志记录

**Comment by 4kangjc** [comment]
没具体测过arm架构，x86_64应该没什么问题

**Comment by 4kangjc** [comment]
`run_async_simple_uthread_test`有一定的问题

**Comment by 4kangjc** [comment]
在每个`whilie(running){}`后加个`sleep(1)`试试？应该是提前结束的原因

**Comment by 4kangjc** [comment]
或者是将`uthread`的`detach`换成`join`，`join`里写`running--`

**Comment by 4kangjc** [comment]
我之前在`qemu`里测`linux ppc64le`也有这个问题

**Comment by 4kangjc** [comment]
这个应该属于测试的问题

**Comment by 4kangjc** [comment]
CI里没有加其他架构里的uthread测试，改天有时间我看看boost怎么做的

**Comment by ChuanqiXu9** [comment]
一方面确实现有的测试没法保证 Uthread 的析构在测试函数结束前完成（有可能有data race），另外也确实是因为少了 CI 架构的原因

**Comment by RainMark** [comment]
uthread结束执行回调时会push了一个task到executor里去析构uthread。正确做法是应该把running--放join lambda里

**Comment by RainMark** [comment]
我又仔细想了下以前case那么写是因为uthread执行结束后肯定是把析构任务push进了executor中，才会走到单测case退出那步。最初的thread pool默认析构会排空还在队列中的task。那么就能确保case结束时，uthread都正确析构了。

https://github.com/alibaba/async_simple/blob/5ef112cccac824e955abfb2c6cb147b074d0b1b1/async_simple/util/ThreadPool.h#L222

当前master分支的thread pool实现貌似丢掉了这个行为。

**Comment by ChuanqiXu9** [comment]
> 我又仔细想了下以前case那么写是因为uthread执行结束后肯定是把析构任务push进了executor中，才会走到单测case退出那步。最初的thread pool默认析构会排空还在队列中的task。那么就能确保case结束时，uthread都正确析构了。
> 
> https://github.com/alibaba/async_simple/blob/5ef112cccac824e955abfb2c6cb147b074d0b1b1/async_simple/util/ThreadPool.h#L222
> 
> 当前master分支的thread pool实现貌似丢掉了这个行为。

感觉 thread pool 还是把任务都排空了再释放比较好，不然 schedule(func) 中的所有 func 都会被执行的假设就不满足了。

**Comment by 4kangjc** [comment]
> > 我又仔细想了下以前case那么写是因为uthread执行结束后肯定是把析构任务push进了executor中，才会走到单测case退出那步。最初的thread pool默认析构会排空还在队列中的task。那么就能确保case结束时，uthread都正确析构了。
> > https://github.com/alibaba/async_simple/blob/5ef112cccac824e955abfb2c6cb147b074d0b1b1/async_simple/util/ThreadPool.h#L222
> > 
> > 当前master分支的thread pool实现貌似丢掉了这个行为。
> 
> 感觉 thread pool 还是把任务都排空了再释放比较好，不然 schedule(func) 中的所有 func 都会被执行的假设就不满足了。

我记得`asio`的`io_context`应该是不排空的，schedule(func) 中的所有 func 都会被执行的假设也不满足了

**Comment by ChuanqiXu9** [comment]
> > > 我又仔细想了下以前case那么写是因为uthread执行结束后肯定是把析构任务push进了executor中，才会走到单测case退出那步。最初的thread pool默认析构会排空还在队列中的task。那么就能确保case结束时，uthread都正确析构了。
> > > https://github.com/alibaba/async_simple/blob/5ef112cccac824e955abfb2c6cb147b074d0b1b1/async_simple/util/ThreadPool.h#L222
> > > 
> > > 当前master分支的thread pool实现貌似丢掉了这个行为。
> > 
> > 
> > 感觉 thread pool 还是把任务都排空了再释放比较好，不然 schedule(func) 中的所有 func 都会被执行的假设就不满足了。
> 
> 我记得`asio`的`io_context`应该是不排空的，schedule(func) 中的所有 func 都会被执行的假设也不满足了

如果使用 asio 的话，需要用 `class AsioExecutor : public async_simple::Executor` 进行一层封装。然后这就是 `AsioExecutor ` 的责任来保证 schedule 里的任务都会被执行；目前 demo example 里的例子可能不太合适，在 coro_rpc 里应该是满足整个假设的。

**Comment by 4kangjc** [comment]
> 

hao

**Comment by 4kangjc** [comment]
> > > > 我又仔细想了下以前case那么写是因为uthread执行结束后肯定是把析构任务push进了executor中，才会走到单测case退出那步。最初的thread pool默认析构会排空还在队列中的task。那么就能确保case结束时，uthread都正确析构了。
> > > > https://github.com/alibaba/async_simple/blob/5ef112cccac824e955abfb2c6cb147b074d0b1b1/async_simple/util/ThreadPool.h#L222
> > > > 
> > > > 当前master分支的thread pool实现貌似丢掉了这个行为。
> > > 
> > > 
> > > 感觉 thread pool 还是把任务都排空了再释放比较好，不然 schedule(func) 中的所有 func 都会被执行的假设就不满足了。
> > 
> > 
> > 我记得`asio`的`io_context`应该是不排空的，schedule(func) 中的所有 func 都会被执行的假设也不满足了
> 
> 如果使用 asio 的话，需要用 `class AsioExecutor : public async_simple::Executor` 进行一层封装。然后这就是 `AsioExecutor ` 的责任来保证 schedule 里的任务都会被执行；目前 demo example 里的例子可能不太合适，在 coro_rpc 里应该是满足整个假设的。

GET

**Comment by 4kangjc** [comment]
> > > > 我又仔细想了下以前case那么写是因为uthread执行结束后肯定是把析构任务push进了executor中，才会走到单测case退出那步。最初的thread pool默认析构会排空还在队列中的task。那么就能确保case结束时，uthread都正确析构了。
> > > > https://github.com/alibaba/async_simple/blob/5ef112cccac824e955abfb2c6cb147b074d0b1b1/async_simple/util/ThreadPool.h#L222
> > > > 
> > > > 当前master分支的thread pool实现貌似丢掉了这个行为。
> > > 
> > > 
> > > 感觉 thread pool 还是把任务都排空了再释放比较好，不然 schedule(func) 中的所有 func 都会被执行的假设就不满足了。
> > 
> > 
> > 我记得`asio`的`io_context`应该是不排空的，schedule(func) 中的所有 func 都会被执行的假设也不满足了
> 
> 如果使用 asio 的话，需要用 `class AsioExecutor : public async_simple::Executor` 进行一层封装。然后这就是 `AsioExecutor ` 的责任来保证 schedule 里的任务都会被执行；目前 demo example 里的例子可能不太合适，在 coro_rpc 里应该是满足整个假设的。

那把thread poll 改回来吧，顺便把thread poll benchmark也改回来

**Comment by 4kangjc** [comment]
我重新看了一遍uthread的代码，觉得`core`的原因应该是`switch_out`换出去那里的问题，测试case中running--是在函数`func`里执行的，然后测试case收到running为0，测试case就已经结束了，但此时thread_context还没有`swith_out`出去，然后当switch_out的时候，测试case的堆栈已经销毁了，所以core掉了
https://github.com/alibaba/async_simple/blob/7cac72f048823818b999bc7fe180661f61d33051/async_simple/uthread/internal/thread.cc#L117
https://github.com/alibaba/async_simple/blob/7cac72f048823818b999bc7fe180661f61d33051/async_simple/uthread/internal/thread.cc#L123

**Comment by RainMark** [comment]
> 我重新看了一遍uthread的代码，觉得`core`的原因应该是`switch_out`换出去那里的问题，测试case中running--是在函数`func`里执行的，然后测试case收到running为0，测试case就已经结束了，但此时thread_context还没有`swith_out`出去，然后当`thread_context`想`switch_out`回到`test case`的时候，测试case的堆栈已经销毁了，所以core掉了
> 
> https://github.com/alibaba/async_simple/blob/7cac72f048823818b999bc7fe180661f61d33051/async_simple/uthread/internal/thread.cc#L117
> 
> 
> https://github.com/alibaba/async_simple/blob/7cac72f048823818b999bc7fe180661f61d33051/async_simple/uthread/internal/thread.cc#L123

嗯，running--确实应该写在join 函数里。executor也需要修复下，不然join函数可能不会被执行。

**Comment by ChuanqiXu9** [comment]
> > 我重新看了一遍uthread的代码，觉得`core`的原因应该是`switch_out`换出去那里的问题，测试case中running--是在函数`func`里执行的，然后测试case收到running为0，测试case就已经结束了，但此时thread_context还没有`swith_out`出去，然后当`thread_context`想`switch_out`回到`test case`的时候，测试case的堆栈已经销毁了，所以core掉了
> > https://github.com/alibaba/async_simple/blob/7cac72f048823818b999bc7fe180661f61d33051/async_simple/uthread/internal/thread.cc#L117
> > 
> > https://github.com/alibaba/async_simple/blob/7cac72f048823818b999bc7fe180661f61d33051/async_simple/uthread/internal/thread.cc#L123
> 
> 嗯，running--确实应该写在join 函数里。executor也需要修复下，不然join函数可能不会被执行。

对，现在的 executor 确实也有问题的，running-- 也应该写在 async 的 callback 里

**Comment by 4kangjc** [comment]
> > 我重新看了一遍uthread的代码，觉得`core`的原因应该是`switch_out`换出去那里的问题，测试case中running--是在函数`func`里执行的，然后测试case收到running为0，测试case就已经结束了，但此时thread_context还没有`swith_out`出去，然后当`thread_context`想`switch_out`回到`test case`的时候，测试case的堆栈已经销毁了，所以core掉了
> > https://github.com/alibaba/async_simple/blob/7cac72f048823818b999bc7fe180661f61d33051/async_simple/uthread/internal/thread.cc#L117
> > 
> > https://github.com/alibaba/async_simple/blob/7cac72f048823818b999bc7fe180661f61d33051/async_simple/uthread/internal/thread.cc#L123
> 
> 嗯，running--确实应该写在join 函数里。executor也需要修复下，不然join函数可能不会被执行。

写在join函数里，`running--`在setValue的时候执行，此时thread_context还是没有switch_out，还是有可能存在那个问题？只是发生的可能性进一步减小了
https://github.com/alibaba/async_simple/blob/b2b7e71087823e3671dc3bfc19c8b281104e7346/async_simple/uthread/internal/thread.cc#L118

**Comment by RainMark** [comment]
> 

setValue这里不会原地执行回调，而是会push task到当前运行的线程里。这样一定是当前uthread switchout了，才轮到join task来执行。

**Comment by 4kangjc** [comment]
> > 
> 
> setValue这里不会原地执行回调，而是会push task到当前运行的线程里。这样一定是当前uthread switchout了，才轮到join task来执行。

GET

**Comment by ChuanqiXu9** [comment]
@4kangjc 可以看这里：https://github.com/alibaba/async_simple/blob/b2b7e71087823e3671dc3bfc19c8b281104e7346/async_simple/uthread/Uthread.h#L63-L76

这里如果设置了调度器的话，是强制进行调度的，也就是不会原地执行；当然如果没有调度器的话就需要用户手动控制了。

**Comment by 4kangjc** [comment]
当然其实是可以通过`_fl_ontop_fcontext`在swap出去后再执行一段函数的

**Comment by 4kangjc** [comment]
> 当然其实是可以通过`_fl_ontop_fcontext`在swap出去后再执行一段函数的



> > 
> 
> setValue这里不会原地执行回调，而是会push task到当前运行的线程里。这样一定是当前uthread switchout了，才轮到join task来执行。
> 
> 保证这个行为是因为配置了future 的forceSched，checkout属性
> 
> https://github.com/alibaba/async_simple/blob/main/async_simple/uthread/Uthread.h#L70

还没具体看Future是怎么实现的

**Comment by ChuanqiXu9** [comment]
> 当然其实是可以通过`_fl_ontop_fcontext`在swap出去后再执行一段函数的

这些就算 hack 了，当然尽可能包装好肯定会更好一些。

**Comment by RainMark** [comment]
> 当然其实是可以通过`_fl_ontop_fcontext`在swap出去后再执行一段函数的

嗯，可以这么干。ontop机制其实之前是没用起来的

**Comment by 4kangjc** [comment]
> > 当然其实是可以通过`_fl_ontop_fcontext`在swap出去后再执行一段函数的
> 
> 嗯，可以这么干。ontop机制其实之前是没用起来的

```cpp
inline void jmp_buf_link::final_switch_out_completed(void* vp) {
    g_current_context = link;
    _fl_ontop_fcontext(link->fcontext, vp, [](transfer_t from) {
        auto p = static_cast<Promise<bool>*>(from.data);
        p->setValue(true);
        return from;
    });
}
```
将`done_.setValue`注释掉，最后的swap_out换掉
```cpp
    // context_.switch_out();
    context_.final_switch_out_completed(&done_);
```

**Comment by RainMark** [comment]
> > > 当然其实是可以通过`_fl_ontop_fcontext`在swap出去后再执行一段函数的
> > 
> > 
> > 嗯，可以这么干。ontop机制其实之前是没用起来的
> 
> ```c++
> inline void jmp_buf_link::final_switch_out_completed(void* vp) {
>     g_current_context = link;
>     _fl_ontop_fcontext(link->fcontext, vp, [](transfer_t from) {
>         auto p = static_cast<Promise<bool>*>(from.data);
>         p->setValue(true);
>         return from;
>     });
> }
> ```
> 
> 将`done_.setValue`注释掉，最后的swap_out换掉
> 
> ```c++
>     // context_.switch_out();
>     context_.final_switch_out_completed(&done_);
> ```

可以新开个issue来讨论吧

**Comment by 4kangjc** [comment]
> > > > 当然其实是可以通过`_fl_ontop_fcontext`在swap出去后再执行一段函数的
> > > 
> > > 
> > > 嗯，可以这么干。ontop机制其实之前是没用起来的
> > 
> > 
> > ```c++
> > inline void jmp_buf_link::final_switch_out_completed(void* vp) {
> >     g_current_context = link;
> >     _fl_ontop_fcontext(link->fcontext, vp, [](transfer_t from) {
> >         auto p = static_cast<Promise<bool>*>(from.data);
> >         p->setValue(true);
> >         return from;
> >     });
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 将`done_.setValue`注释掉，最后的swap_out换掉
> > ```c++
> >     // context_.switch_out();
> >     context_.final_switch_out_completed(&done_);
> > ```
> 
> 可以新开个issue来讨论吧

OK，暂时没有换的打算，先这样吧，后面有需求再说
