### ISSUE TITLE
Remove MoveWrapper

### ISSUE THREAD

**Issue by RainMark** [alibaba/async_simple#24]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

remove MoveWrapper.h
the following usage is so ugly
```c++
Promise p;
auto func = [wrapper = MoveWrapper(std::move(p))]() {
  wrapper.get().setValue()
}
```

### Anything else

TODO

See: #20 

- Remove Promise's copy assignment operator, remove promiseRef_ member in FutureState.h
- Delete MoveWrapper.h
- Try to fix the problem of std::function require the captured object be copyable

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
can be closed?

**Comment by RainMark** [comment]
> can be closed?

no，we haven't removed the MoveWrapper

**Comment by RainMark** [comment]
the c++23 introduced std::move_only_function https://en.cppreference.com/w/cpp/utility/functional/move_only_function

two solutions

1. used `std::move_only_function` or seastar's non copyable_function to replace std::function
2. noticed we just use std::function<void()> for task schedule, we can implement a special type-erased task used to lambda schedule. no need a complete implemented move_only_function

eg: 

```c++
class task {
public:
    virtual ~task() {}
    virtual void invoke() = 0;
};

template <class T>
class lambda_task : public task {
public:
    explicit lambda_task(T&& lambda) : lambda_(std::forward<T>(lambda)) {}
    void invoke() {
        lambda_();
    }
private:
    T lambda_;
};

template <class T>
std::unique_ptr<task> make_task(T&& lambda) {
    return std::make_unique<lambda_task<T>>(std::forward<T>(lambda));
}

void schedule(std::unique_ptr<task>&& t) {
    t->invoke();
}

int main() {
    auto p = std::make_unique<int>(1);
    auto t = make_task([p = std::move(p)]() { std::cout << *p << std::endl; });
    schedule(std::move(t));
    return 0;
}

```

**Comment by qicosmos** [comment]
I'm a little afraid the performance would be decreased.

**Comment by RainMark** [comment]
> I'm a little afraid the performance would be decreased.

I can make a performance test to compare it

**Comment by 4kangjc** [comment]
1. `std::move_only_function`可以参考[Tencent flare function](https://github.com/Tencent/flare/blob/master/flare/base/function.h)
2. 类型擦除或许可以不用虚函数实现，通过`std::shared_ptr`+`template`可实现？

**Comment by 4kangjc** [comment]
> > 2. 类型擦除或许可以不用虚函数实现，通过`std::shared_ptr`+`template`可实现？
> 
> 可以给出一个例子吗？对比benchmark下什么的

```c++
#include <iostream>
#include <type_traits>
#include <functional>
#include <memory>
#include <utility>
#include <cassert>

template <typename Callable>
void task_proxy(void* vp) {
    auto invoker_ptr(static_cast<Callable*>(vp));
    if (invoker_ptr) {
        (*invoker_ptr)();
    }
}

class task {
public:
    template <class Fn, typename = std::enable_if_t<std::is_invocable_v<Fn&&>>>
    task(Fn&& func) {
        using Wrapper = typename std::decay_t<Fn>;
        auto __vp = new Wrapper(std::forward<Fn>(func));
        proxy = &task_proxy<Wrapper>;
        vp.reset(__vp);
    }

    void operator()() const { proxy(vp.get()); }
    explicit operator bool() { return proxy.operator bool(); }
private:
    std::function<void(void*)> proxy;
    std::shared_ptr<void> vp;
};

void print() {
    std::cout << "Hello World\n";
}

int main() {
    const char* s = "Hello World";
    auto uptr = std::make_unique<int>(2);
    // Test lambda
    task t([u = std::move(uptr), s]() {
        assert(*u = 2);
        std::cout << s << std::endl;
    });
    t();
    
    // Test function name
    task t2(print);
    t2();

    // Test function pointer
    task t3(&print);
    t3();

    // Test member method
    struct A {
        void operator()() {}
    };
    A a;
    task t4(a);
    t4();
    // Test bind
    task t5(std::bind(&A::operator(), a));
    t5();
}
```
先给个实现把

**Comment by RainMark** [comment]
> > > 2. 类型擦除或许可以不用虚函数实现，通过`std::shared_ptr`+`template`可实现？
> > 
> > 
> > 可以给出一个例子吗？对比benchmark下什么的
> 
> ```c++
> #include <iostream>
> #include <type_traits>
> #include <functional>
> #include <memory>
> #include <utility>
> #include <cassert>
> 
> template <typename Callable>
> void task_proxy(void* vp) {
>     auto invoker_ptr(static_cast<Callable*>(vp));
>     if (invoker_ptr) {
>         (*invoker_ptr)();
>     }
> }
> 
> class task {
> public:
>     template <class Fn, typename = std::enable_if_t<std::is_invocable_v<Fn&&>>>
>     task(Fn&& func) {
>         using Wrapper = typename std::decay_t<Fn>;
>         auto __vp = new Wrapper(std::forward<Fn>(func));
>         proxy = &task_proxy<Wrapper>;
>         vp.reset(__vp);
>     }
> 
>     void operator()() const { proxy(vp.get()); }
>     explicit operator bool() { return proxy.operator bool(); }
> private:
>     std::function<void(void*)> proxy;
>     std::shared_ptr<void> vp;
> };
> 
> void print() {
>     std::cout << "Hello World\n";
> }
> 
> int main() {
>     const char* s = "Hello World";
>     auto uptr = std::make_unique<int>(2);
>     // Test lambda
>     task t([u = std::move(uptr), s]() {
>         assert(*u = 2);
>         std::cout << s << std::endl;
>     });
>     t();
>     
>     // Test function name
>     task t2(print);
>     t2();
> 
>     // Test function pointer
>     task t3(&print);
>     t3();
> 
>     // Test member method
>     struct A {
>         void operator()() {}
>     };
>     A a;
>     task t4(a);
>     t4();
>     // Test bind
>     task t5(std::bind(&A::operator(), a));
>     t5();
> }
> ```
> 
> 先给个实现把

赞，我们之前还没来得及benchmark对比新方案前后性能，你看你是否有时间一起连同你的方案benchmark对比下。看看不同方案task创建，传递和invoke的开销

**Comment by 4kangjc** [comment]
> > > > 2. 类型擦除或许可以不用虚函数实现，通过`std::shared_ptr`+`template`可实现？
> > > 
> > > 
> > > 可以给出一个例子吗？对比benchmark下什么的
> > 
> > 
> > ```c++
> > #include <iostream>
> > #include <type_traits>
> > #include <functional>
> > #include <memory>
> > #include <utility>
> > #include <cassert>
> > 
> > template <typename Callable>
> > void task_proxy(void* vp) {
> >     auto invoker_ptr(static_cast<Callable*>(vp));
> >     if (invoker_ptr) {
> >         (*invoker_ptr)();
> >     }
> > }
> > 
> > class task {
> > public:
> >     template <class Fn, typename = std::enable_if_t<std::is_invocable_v<Fn&&>>>
> >     task(Fn&& func) {
> >         using Wrapper = typename std::decay_t<Fn>;
> >         auto __vp = new Wrapper(std::forward<Fn>(func));
> >         proxy = &task_proxy<Wrapper>;
> >         vp.reset(__vp);
> >     }
> > 
> >     void operator()() const { proxy(vp.get()); }
> >     explicit operator bool() { return proxy.operator bool(); }
> > private:
> >     std::function<void(void*)> proxy;
> >     std::shared_ptr<void> vp;
> > };
> > 
> > void print() {
> >     std::cout << "Hello World\n";
> > }
> > 
> > int main() {
> >     const char* s = "Hello World";
> >     auto uptr = std::make_unique<int>(2);
> >     // Test lambda
> >     task t([u = std::move(uptr), s]() {
> >         assert(*u = 2);
> >         std::cout << s << std::endl;
> >     });
> >     t();
> >     
> >     // Test function name
> >     task t2(print);
> >     t2();
> > 
> >     // Test function pointer
> >     task t3(&print);
> >     t3();
> > 
> >     // Test member method
> >     struct A {
> >         void operator()() {}
> >     };
> >     A a;
> >     task t4(a);
> >     t4();
> >     // Test bind
> >     task t5(std::bind(&A::operator(), a));
> >     t5();
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 先给个实现把
> 
> 赞，我们之前还没来得及benchmark对比新方案前后性能，你看你是否有时间一起连同你的方案benchmark对比下。看看不同方案task创建，传递和invoke的开销

行，到时候弄下

**Comment by 4kangjc** [comment]
我觉得用folly的Function也行

**Comment by 4kangjc** [comment]
> 我觉得用folly的Function也行

直接扒一份`move_only_function`的代码也行
