### ISSUE TITLE
MSVC Compiler Error C4737 by async_simple::coro::Lazy

### ISSUE THREAD

**Issue by poor-circle** [alibaba/async_simple#256]
### Search before asking

- [√ ] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

A simple function cause compile error in MSVC Release.

```cpp
#include "async_simple/coro/Lazy.h"
#include "async_simple/coro/SyncAwait.h"

async_simple::coro::Lazy<int> test(int val) { co_return val; }

int main() { return async_simple::coro::syncAwait(test(0)); }
```

error info:

```
main.cpp(19): error C4737: 无法执行所需尾调用。性能可能会降级。
```

### Reproduction way

VS 2022 17.3.4 Release

### Anything else

Add `/EHa` can fix this problem. It seems a bug by optimization in MSVC Release.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by poor-circle** [comment]
[bug report](https://developercommunity.visualstudio.com/t/coroutine-compilation-resulting-in-error-c4737-una/1510427)

**Comment by 4kangjc** [comment]
https://github.com/alibaba/async_simple/blob/2f4f0660ae84947a27f6dfba3a74a65989195a32/CMakeLists.txt#L99

Doesn't `/Eha` already exist?

**Comment by poor-circle** [comment]
> https://github.com/alibaba/async_simple/blob/2f4f0660ae84947a27f6dfba3a74a65989195a32/CMakeLists.txt#L99
> 
> Doesn't `/Eha` already exist?


Yes, it already exist. But this is are a head-only library. So we should document it for msvc user.

**Comment by poor-circle** [comment]
> https://github.com/alibaba/async_simple/blob/2f4f0660ae84947a27f6dfba3a74a65989195a32/CMakeLists.txt#L99
> 
> Doesn't `/Eha` already exist?

Yes, it already exist. But this is a head-only library. So we should document it for msvc user.

**Comment by 4kangjc** [comment]
> > https://github.com/alibaba/async_simple/blob/2f4f0660ae84947a27f6dfba3a74a65989195a32/CMakeLists.txt#L99
> > 
> > Doesn't `/Eha` already exist?
> 
> Yes, it already exist. But this is a head-only library. So we should document it for msvc user.

I see.

**Comment by ChuanqiXu9** [comment]
@poor-circle Could you help to document this in our documents?

**Comment by 4kangjc** [comment]
> @poor-circle Could you help to document this in our documents?

Conan CI好像挂了

**Comment by poor-circle** [comment]
> @poor-circle Could you help to document this in our documents?

OK
