### ISSUE TITLE
Some questions about collectAny

### ISSUE THREAD

**Issue by chloro-pn** [alibaba/async_simple#260]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
collectAny接口总是等待第一个协程返回而不是最先完成的协程返回

### Reproduction way
https://github.com/chloro-pn/bridge/blob/master/test/async_simple_test.cc#L39 这个测试可以复现

### Anything else
看了下源码，这里没有像collectAllPara一样将协程交给executor调度，这个接口就是串行语义么？如果是的话是不是缺少
一个collectAnyPara接口，我想这个接口更符合实际用途。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by 4kangjc** [comment]
https://github.com/chloro-pn/bridge/blob/19e194875e402c4169cf5ccd8d606cfede802732/test/async_simple_test.cc#L28
这里改成reschedule 下面用via绑定executor

**Comment by 4kangjc** [comment]
确实没有collectanypara这个接口

**Comment by chloro-pn** [comment]
这么处理是ok的：https://github.com/chloro-pn/bridge/blob/master/test/async_simple_test.cc#L27  测试通过

这样的话，[文档](https://github.com/alibaba/async_simple/blob/main/docs/docs.cn/Lazy.md#collectany)这里需要修正一下。
或者把接口collectAny就改成并行语义，这样就与文档一致了（串行语义的collectAny实际上没有意义）。

**Comment by ChuanqiXu9** [comment]
> 这么处理是ok的：https://github.com/chloro-pn/bridge/blob/master/test/async_simple_test.cc#L27 测试通过
> 
> 这样的话，[文档](https://github.com/alibaba/async_simple/blob/main/docs/docs.cn/Lazy.md#collectany)这里需要修正一下。 或者把接口collectAny就改成并行语义，这样就与文档一致了（串行语义的collectAny实际上没有意义）。

现在这个代码里的写法是对的。

这里确实我们文档没写好，我再补一下，关于你这里的代码：

```
Lazy<void> AnyTest(size_t& idx, size_t& res) {
  std::vector<Lazy<size_t>> cors;
  cors.push_back(std::move(cor(5)));
  cors.push_back(std::move(cor(1)));
  cors.push_back(std::move(cor(3)));

  auto ret = co_await collectAny(std::move(cors));
  idx = ret._idx;
  res = ret._value.value();
  co_return;
}
```

这么写的语义是：“先跑 cors[0] 直到其挂起，然后跑 cors[1] 直到其挂起， 。。。然后返回第一个结束的任务“。现在写法是：

```

Lazy<size_t> cor(size_t sec) {
  std::this_thread::sleep_for(std::chrono::seconds(sec));
  std::cout << " cor " << sec << " return" << std::endl;
  co_return sec;
}
```

这么写实际上是挂起当前线程而不是挂起当前协程了，所以挂起之后不会跑 cors[1]。之后 cors[0] 执行结束就直接返回了，所以才有这么个现象。我改下文档吧。

**Comment by 4kangjc** [comment]
> > 这么处理是ok的：https://github.com/chloro-pn/bridge/blob/master/test/async_simple_test.cc#L27 测试通过
> > 这样的话，[文档](https://github.com/alibaba/async_simple/blob/main/docs/docs.cn/Lazy.md#collectany)这里需要修正一下。 或者把接口collectAny就改成并行语义，这样就与文档一致了（串行语义的collectAny实际上没有意义）。
> 
> 现在这个代码里的写法是对的。
> 
> 这里确实我们文档没写好，我再补一下，关于你这里的代码：
> 
> ```c++
> Lazy<void> AnyTest(size_t& idx, size_t& res) {
>   std::vector<Lazy<size_t>> cors;
>   cors.push_back(std::move(cor(5)));
>   cors.push_back(std::move(cor(1)));
>   cors.push_back(std::move(cor(3)));
> 
>   auto ret = co_await collectAny(std::move(cors));
>   idx = ret._idx;
>   res = ret._value.value();
>   co_return;
> }
> ```
> 
> 这么写的语义是：“先跑 cors[0] 直到其挂起，然后跑 cors[1] 直到其挂起， 。。。然后返回第一个结束的任务“。现在写法是：
> 
> ```c++
> Lazy<size_t> cor(size_t sec) {
>   std::this_thread::sleep_for(std::chrono::seconds(sec));
>   std::cout << " cor " << sec << " return" << std::endl;
>   co_return sec;
> }
> ```
> 
> 这么写实际上是挂起当前线程而不是挂起当前协程了，所以挂起之后不会跑 cors[1]。之后 cors[0] 执行结束就直接返回了，所以才有这么个现象。我改下文档吧。

`CollectAnyResult`要不要提供一下`index()`, `value()`的接口啊，`_idx`和`_value`有点怪

**Comment by ChuanqiXu9** [comment]
> 

确实是应该的。。我觉得可以加一下，但还是保持对 _idx 和 _value 的访问吧，不然会有兼容性问题

**Comment by 4kangjc** [comment]
> > 
> 
> 确实是应该的。。我觉得可以加一下，但还是保持对 _idx 和 _value 的访问吧，不然会有兼容性问题

嗯

**Comment by chloro-pn** [comment]
哦哦，明白了
