### ISSUE TITLE
`TryAwaiter` may need `coAwait` method

### ISSUE THREAD

**Issue by 4kangjc** [alibaba/async_simple#276]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
https://github.com/alibaba/async_simple/blob/bfcd39108f03bf600abc2c9aa0f0dd70b68162a7/async_simple/coro/Lazy.h#L276-L281

`ViaCoroutine` is not needed when `co_await lazy`, but `ViaCoroutine` is used when `co_await lazy.coAwaitTry`

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
在 Lazy 中 `co_await Lazy::coAwaitTry()` 时会调用 `ViaCoroutine` 确实是个问题。但直接在 TryAwaiter 里加 coAwait 方法感觉不太好，太 hack 了，我再想想怎么办吧

**Comment by 4kangjc** [comment]
> 在 Lazy 中 `co_await Lazy::coAwaitTry()` 时会调用 `ViaCoroutine` 确实是个问题。但直接在 TryAwaiter 里加 coAwait 方法感觉不太好，太 hack 了，我再想想怎么办吧 

恩，在transform里加一下？

**Comment by ChuanqiXu9** [comment]
> 

在 Transform 里加也不太对，`co_await Lazy::coAwaitTry()` 的期望行为应该把调度器传给 Lazy。但现在 Lazy 和 RescheduleLazy 是共用一个 coAwaitTry 的

**Comment by 4kangjc** [comment]
> > 
> 
> 在 Transform 里加也不太对，`co_await Lazy::coAwaitTry()` 的期望行为应该把调度器传给 Lazy。但现在 Lazy 和 RescheduleLazy 是共用一个 coAwaitTry 的

嗯，现有的`coAwaitTry`不会传递调度器;  那感觉还是加一个coAwait比较好，`transform`不太合适
```cpp
auto await_transform(TryAwaiter&& awaiter) {
    awaiter._coro.promise()._executor = _executor;
    return std::move(awaiter);
}
```

```cpp
auto coAwait(Executor* ex) {
    _coro.promise()._executor = ex;
    return std::move(*this);
}
```

**Comment by ChuanqiXu9** [comment]
直接加也不对，因为 RescheudleLazy 也可以调用 coAwaitTry 方法，但我们不能对 RescheudleLazy 设置调度器

**Comment by 4kangjc** [comment]
> 直接加也不对，因为 RescheudleLazy 也可以调用 coAwaitTry 方法，但我们不能对 RescheudleLazy 设置调度器

`RescheduleLazy`不是自带调度器吗

**Comment by 4kangjc** [comment]
> 直接加也不对，因为 RescheudleLazy 也可以调用 coAwaitTry 方法，但我们不能对 RescheudleLazy 设置调度器

判断一下是否已经存在调度器？

**Comment by 4kangjc** [comment]
https://github.com/alibaba/async_simple/issues/163
得关一下，现在`RescheduleLazy`还是可以`co_await RescheduleLazy`的
和文档冲突了

RescheduleLazy 在语义上是绑定了 Executor 的 Lazy。RescheduleLazy 在 co_await Lazy 时并不会使用对称变换立即执行 Lazy，而是将唤醒 Lazy 的任务提交到 RescheduleLazy 绑定的 Executor 中。因为语义上 RescheduleLazy 也是 Lazy，所以 RescheduleLazy 也能使用 Lazy 的接口 co_await、.start 和 syncAwait.

**Comment by ChuanqiXu9** [comment]
> #163 得关一下，现在`RescheduleLazy`还是可以`co_await RescheduleLazy`的 和文档冲突了
> 
> RescheduleLazy 在语义上是绑定了 Executor 的 Lazy。RescheduleLazy 在 co_await Lazy 时并不会使用对称变换立即执行 Lazy，而是将唤醒 Lazy 的任务提交到 RescheduleLazy 绑定的 Executor 中。因为语义上 RescheduleLazy 也是 Lazy，所以 RescheduleLazy 也能使用 Lazy 的接口 co_await、.start 和 syncAwait.

按设计来说不应该关 163 应该改下文档，只是一下子没想到怎么限制用户不 co_await RescheduleLazy.

**Comment by ChuanqiXu9** [comment]
> > 直接加也不对，因为 RescheudleLazy 也可以调用 coAwaitTry 方法，但我们不能对 RescheudleLazy 设置调度器
> 
> 判断一下是否已经reschedule ? 或者是是否存在`executor`？通过`setEx`设置调度器的`Lazy`要覆盖吗
> 
> ```c++
> auto coAwait(Executor* ex) {
>     if constexpr (!reschedule) {
>         _coro.promise()._executor = ex;
>     }
>     return std::move(*this);
> }
> ```

通过 reschedule 判断好像可以，setEx 的属于特殊用法，可以直接覆盖应该没问题

**Comment by 4kangjc** [comment]
> 

hmmm, 直接删掉`operator co_await`就行... 毕竟`Lazy`走的是`coAwait`，不是`operator co_await`

**Comment by 4kangjc** [comment]
> > #163 得关一下，现在`RescheduleLazy`还是可以`co_await RescheduleLazy`的 和文档冲突了
> > RescheduleLazy 在语义上是绑定了 Executor 的 Lazy。RescheduleLazy 在 co_await Lazy 时并不会使用对称变换立即执行 Lazy，而是将唤醒 Lazy 的任务提交到 RescheduleLazy 绑定的 Executor 中。因为语义上 RescheduleLazy 也是 Lazy，所以 RescheduleLazy 也能使用 Lazy 的接口 co_await、.start 和 syncAwait.
> 
> 按设计来说不应该关 163 应该改下文档，只是一下子没想到怎么限制用户不 co_await RescheduleLazy.

如果不允许`co_await RescheduleLazy`的话，在`Lazy`中`co_await RescheduleLazy.coAwaitTry`也是不允许的
```cpp
auto coAwait(Executor* ex) {
    if constexpr (!reschedule) {
        assert(false);
    }
    return std::move(*this);
}
```
`start`是在`DeatchCoroutine`中，与`coAwait`无关

**Comment by ChuanqiXu9** [comment]
> hmmm, 直接删掉`operator co_await`就行... 毕竟`Lazy`走的是`coAwait`，不是`operator co_await`

不能这么删吧。。这样 Lazy 在其他环境中都不是 awaitable 了

**Comment by ChuanqiXu9** [comment]
> > > #163 得关一下，现在`RescheduleLazy`还是可以`co_await RescheduleLazy`的 和文档冲突了
> > > RescheduleLazy 在语义上是绑定了 Executor 的 Lazy。RescheduleLazy 在 co_await Lazy 时并不会使用对称变换立即执行 Lazy，而是将唤醒 Lazy 的任务提交到 RescheduleLazy 绑定的 Executor 中。因为语义上 RescheduleLazy 也是 Lazy，所以 RescheduleLazy 也能使用 Lazy 的接口 co_await、.start 和 syncAwait.
> > 
> > 
> > 按设计来说不应该关 163 应该改下文档，只是一下子没想到怎么限制用户不 co_await RescheduleLazy.
> 
> 如果不允许`co_await RescheduleLazy`的话，在`Lazy`中`co_await RescheduleLazy.coAwaitTry`也是不允许的
> 
> ```c++
> auto coAwait(Executor* ex) {
>     if constexpr (!reschedule) {
>         logicAssert(false, "RescheduleLazy should be only allowed in DetachedCoroutine");
>     }
>     _coro.promise()._executor = ex;
>     return std::move(*this);
> }
> ```
> 
> `start`是在`DeatchCoroutine`中，与`coAwait`无关

有道理，我有点晕了，感觉是可以这么改的

**Comment by 4kangjc** [comment]
> > hmmm, 直接删掉`operator co_await`就行... 毕竟`Lazy`走的是`coAwait`，不是`operator co_await`
> 
> 不能这么删吧。。这样 Lazy 在其他环境中都不是 awaitable 了

hmm, `Lazy`还会在除`Lazy`和`RescheduleLazy`外的环境下`co_await`吗

**Comment by 4kangjc** [comment]
> > > hmmm, 直接删掉`operator co_await`就行... 毕竟`Lazy`走的是`coAwait`，不是`operator co_await`
> > 
> > 
> > 不能这么删吧。。这样 Lazy 在其他环境中都不是 awaitable 了
> 
> hmm, `Lazy`还会在除`Lazy`和`RescheduleLazy`外的环境下`co_await`吗

hmm, 而且我是说在`RescheduleLazy`里删掉，不是`LazyBase`，应该影响不到`Lazy`
```cpp
// RescheduleLazy should be only allowed in DetachedCoroutine
    auto operator co_await() = delete;
```

**Comment by 4kangjc** [comment]
> > > 直接加也不对，因为 RescheudleLazy 也可以调用 coAwaitTry 方法，但我们不能对 RescheudleLazy 设置调度器
> > 
> > 
> > 判断一下是否已经reschedule ? 或者是是否存在`executor`？通过`setEx`设置调度器的`Lazy`要覆盖吗
> > ```c++
> > auto coAwait(Executor* ex) {
> >     if constexpr (!reschedule) {
> >         _coro.promise()._executor = ex;
> >     }
> >     return std::move(*this);
> > }
> > ```
> 
> 通过 reschedule 判断好像可以，setEx 的属于特殊用法，可以直接覆盖应该没问题。用 reschedule 判断的问题是如果出现类型强转的话会有问题，但一般应该没这么用的。

强转好像也不会出问题。
```cpp
template <bool r>
struct Base {
public:
  void f() {
    if constexpr (r) {
      std::cout << "Yes" << std::endl; 
    } else {
      std::cout << "No" << std::endl;
    }
  }
};

struct A : Base<false> {

};

struct B : Base<true> {

};

int main() {
  auto a = new A();
  a->f();   // No
  auto b = (B*)a;
  b->f();   // Yes
}

```

**Comment by ChuanqiXu9** [comment]
> > > > hmmm, 直接删掉`operator co_await`就行... 毕竟`Lazy`走的是`coAwait`，不是`operator co_await`
> > > 
> > > 
> > > 不能这么删吧。。这样 Lazy 在其他环境中都不是 awaitable 了
> > 
> > 
> > hmm, `Lazy`还会在除`Lazy`和`RescheduleLazy`外的环境下`co_await`吗
> 
> hmm, 而且我是说在`RescheduleLazy`里删掉，不是`LazyBase`，应该影响不到`Lazy`
> 
> ```c++
> // RescheduleLazy should be only allowed in DetachedCoroutine
>     auto operator co_await() = delete;
> ```

好像也可以啊

**Comment by 4kangjc** [comment]
> > > > hmmm, 直接删掉`operator co_await`就行... 毕竟`Lazy`走的是`coAwait`，不是`operator co_await`
> > > 
> > > 
> > > 不能这么删吧。。这样 Lazy 在其他环境中都不是 awaitable 了
> > 
> > hmm, `Lazy`还会在除`Lazy`和`RescheduleLazy`外的环境下`co_await`吗
> 
> 主要是为了保持 awaitable 的性质，毕竟一个不能 co_await 的 Task 很奇怪。一方面这里限制用法会比较奇怪，另外一方面  最起码还有 Generator 类型的 Coroutine 来着。

那ValueAwaiter里也要加下？不然其他环境调度器也没法传递下去。

**Comment by ChuanqiXu9** [comment]
> > > > > hmmm, 直接删掉`operator co_await`就行... 毕竟`Lazy`走的是`coAwait`，不是`operator co_await`
> > > > 
> > > > 
> > > > 不能这么删吧。。这样 Lazy 在其他环境中都不是 awaitable 了
> > > 
> > > 
> > > hmm, `Lazy`还会在除`Lazy`和`RescheduleLazy`外的环境下`co_await`吗
> > 
> > 
> > 主要是为了保持 awaitable 的性质，毕竟一个不能 co_await 的 Task 很奇怪。一方面这里限制用法会比较奇怪，另外一方面  最起码还有 Generator 类型的 Coroutine 来着。
> 
> 其他环境调度器也没法传递下去。这个估计得说明一下

其他环境里的语义就由其他环境定义吧。上面的意思是 Lazy 的 operator co_await 不应该删掉，不然就不算 awaitable 了，语义很奇怪。不过既然不准备删 Lazy 的 operator co_await，那这个事其实也没什么关系了。

**Comment by 4kangjc** [comment]
> > > > > > hmmm, 直接删掉`operator co_await`就行... 毕竟`Lazy`走的是`coAwait`，不是`operator co_await`
> > > > > 
> > > > > 
> > > > > 不能这么删吧。。这样 Lazy 在其他环境中都不是 awaitable 了
> > > > 
> > > > 
> > > > hmm, `Lazy`还会在除`Lazy`和`RescheduleLazy`外的环境下`co_await`吗
> > > 
> > > 
> > > 主要是为了保持 awaitable 的性质，毕竟一个不能 co_await 的 Task 很奇怪。一方面这里限制用法会比较奇怪，另外一方面  最起码还有 Generator 类型的 Coroutine 来着。
> > 
> > 其他环境调度器也没法传递下去。这个估计得说明一下
> 
> 其他环境里的语义就由其他环境定义吧。上面的意思是 Lazy 的 operator co_await 不应该删掉，不然就不算 awaitable 了，语义很奇怪。不过既然不准备删 Lazy 的 operator co_await，那这个事其实也没什么关系了。

恩

**Comment by 4kangjc** [comment]
hmmm, `collectAllVariadicImpl`中的`makeWraperTask`用到了`co_await RescheduleLazy`, 这个怎么改

**Comment by ChuanqiXu9** [comment]
> hmmm, `collectAllVariadicImpl`中的`makeWraperTask`用到了`co_await RescheduleLazy`, 这个怎么改

hmmm 这就属于之前没发现的 defect 了，现在想到的一种改法是把 collectAllVariadicImpl 改造成 CollectAnyVariadicAwaiter 的样子

**Comment by 4kangjc** [comment]
> > hmmm, `collectAllVariadicImpl`中的`makeWraperTask`用到了`co_await RescheduleLazy`, 这个怎么改
> 
> hmmm 这就属于之前没发现的 defect 了，现在想到的一种改法是把 collectAllVariadicImpl 改造成 CollectAnyVariadicAwaiter 的样子

OK
