### ISSUE TITLE
[Enhancement] An RAII coroutine type

### ISSUE THREAD

**Issue by Minecraft1248** [alibaba/async_simple#296]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
How about adding a new coroutine type co_resource<T> ;)?
vector<bool>'s blog post [co_resource<T>: An RAII coroutine](https://vector-of-bool.github.io/2021/12/30/co_resource.html)
Implementation of co_resource<T> in [neo_fun](https://github.com/vector-of-bool/neo-fun/blob/develop/src/neo/co_resource.hpp)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by 4kangjc** [comment]
This method is not good for handling return values and exceptions

**Comment by ChuanqiXu9** [comment]
The design and intention looks a little bit weird to me. Since it looks like a generator which can only yield once.

**Comment by Minecraft1248** [comment]
The coroutine type **serves as a more concise alternative to a regular RAII**. Consider the following code:
```cpp
//regular RAII
struct file_scope {
  std::FILE* file;

  file_scope(const char* path)
    : file(std::fopen(path, "rb")) {}

  ~file_scope() {
    std::fclose(file);
  }
};//warp the std::FILE* in a struct
int foo() {
  file_scope("hi.txt");  //create it
  //and then use it
  return 0;  //the destructor automatically close the file handle
}

//with co_resource<>
int foo() {
  co_resource<std::FILE*> cr = [](const char* path) -> co_resource<std::FILE*> {
    std::FILE* file;
    file = std::fopen(path, "rb");
    co_yield file;
    std::fclose(file);
  }("hi.txt");
  //and then use it, but through the co_resource<FILE*>;
  return 0;  //the resumed coroutine automatically close the file handle
}
```
By using the co_resource<>, we can simply get cleaner syntax when we just want a simple RAII handle. Also, we can express some complicated RAII scenes more easily.

**Comment by ChuanqiXu9** [comment]
But it is still odd that the coroutine type can only have exactly one `co_yield` and we don't have any method to constraint that. Also I feel it reads better to have something like `on_exit(callable)`.

**Comment by ChuanqiXu9** [comment]
Close as not planned.
