### ISSUE TITLE
bazel config_setting async_simple_enable_tests is not useful

### ISSUE THREAD

**Issue by chloro-pn** [alibaba/async_simple#297]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
使用bazel编译的时候，async_simple_enable_tests这个配置选项是无效的，看了下配置文件，测试代码的构建没有依赖这个选项

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by 4kangjc** [comment]
是的，这个选项无效，因为bazel不需要这种形式，如果仅仅想编译库的话，可以`bazel build :async_simple`

**Comment by 4kangjc** [comment]
> 是的，这个选项无效，因为bazel不需要这种形式，如果仅仅想编译库的话，可以`bazel build :async_simple`

只是写的时候忘记去掉了

**Comment by chloro-pn** [comment]
> > 是的，这个选项无效，因为bazel不需要这种形式，如果仅仅想编译库的话，可以`bazel build :async_simple`
> 
> 只是写的时候忘记去掉了

这个选项加不加都可以，不过如果不加的话最好把不需要的选项删掉。。容易造成误解

**Comment by 4kangjc** [comment]
> > > 是的，这个选项无效，因为bazel不需要这种形式，如果仅仅想编译库的话，可以`bazel build :async_simple`
> > 
> > 只是写的时候忘记去掉了
> 
> 这个选项加不加都可以，不过如果不加的话最好把不需要的选项删掉。。容易造成误解

嗯

**Comment by ChuanqiXu9** [comment]
Closed by https://github.com/alibaba/async_simple/pull/298
