### ISSUE TITLE
Consideration about setting shared library version

### ISSUE THREAD

**Issue by topazus** [alibaba/async_simple#306]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

The versioned shared library specifies its API version, it can be useful for maintaining backward compatibility when updating shared libraries.

Ref: https://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
Thanks for the suggestion. Will do.
