### ISSUE TITLE
有没有更详细的windows版本安装流程，编译环节一直出现问题

### ISSUE THREAD

**Issue by bbj767475974** [alibaba/async_simple#308]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by 4kangjc** [comment]
cmake编译可以参考workflow的Windows CI，matrix.mode 可以是Release或者Debug
```cmake
# Generate Project
cmake -B Build/${{ matrix.mode }} -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DRFK_DEV=1 -G "Visual Studio 16 2019" -A x64
# Build
cmake --build Build/${{ matrix.mode }} --config ${{ matrix.mode }} --verbose
```
Bazel 编译使用 `bazel build ...`就行，bazel install可以看一下， https://bazel.build/install/windows

**Comment by ChuanqiXu9** [comment]
可以提供具体的报错信息的话会更有帮助

**Comment by fantasy-peak** [comment]
https://github.com/xmake-io/xmake-repo/blob/94cc1244f79f843dca5d1391ab5b16fe67286913/packages/a/async_simple/xmake.lua#L17   cmake编译参数可以参考这个

**Comment by bbj767475974** [comment]
![1685018077754](https://github.com/alibaba/async_simple/assets/61446077/ab079d8a-2a09-445b-aa80-4607384e41ec)
这是使用bazel build...编译出现的错误

**Comment by bbj767475974** [comment]
[60/62] Linking CXX executable demo_example\http_client.exe
  [61/62] Building CXX object async_simple\coro\test\CMakeFiles\async_simple_coro_test.dir\LazyTest.cpp.obj
  FAILED: async_simple/coro/test/CMakeFiles/async_simple_coro_test.dir/LazyTest.cpp.obj 
  "E:\visual studio\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe"  /nologo /TP -DASYNC_SIMPLE_HAS_NOT_AIO -ID:\c++\async4\async_simple-main -external:I D:\c++\async4\async_simple-main\out\build\x64-Debug\_deps\googletest-src\googletest\include -external:I D:\c++\async4\async_simple-main\out\build\x64-Debug\_deps\googletest-src\googlemock\include -external:I D:\c++\async4\async_simple-main\out\build\x64-Debug\_deps\googletest-src\googletest -external:I D:\c++\async4\async_simple-main\out\build\x64-Debug\_deps\googletest-src\googlemock -external:W0 /std:c++20 /Zc:__cplusplus /await:strict /EHa /Zi /Ob0 /Od /RTC1 /MTd -MDd -std:c++20 /showIncludes /Foasync_simple\coro\test\CMakeFiles\async_simple_coro_test.dir\LazyTest.cpp.obj /Fdasync_simple\coro\test\CMakeFiles\async_simple_coro_test.dir\ /FS -c D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp
D:\c++\async4\async_simple-main\out\build\x64-Debug\cl : 命令行 warning D9025: 正在重写“/MTd”(用“/MDd”)
D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(930): warning C4305: “if”: 从“size_t”到“bool”截断
  D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(930): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAll<async_simple::coro::Lazy,int,double,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>(async_simple::coro::Lazy<int>,async_simple::coro::Lazy<double>,async_simple::coro::Lazy<std::basic_string<char,std::char_traits<char>,std::allocator<char>>>)”的引用
D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(957): warning C4305: “if”: 从“size_t”到“bool”截断
  D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(957): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAll<async_simple::coro::Lazy,int,void,void>(async_simple::coro::Lazy<int>,async_simple::coro::Lazy<void>,async_simple::coro::Lazy<void>)”的引用
D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(996): warning C4305: “if”: 从“size_t”到“bool”截断
  D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(996): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAll<async_simple::coro::RescheduleLazy,T,double,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>(async_simple::coro::RescheduleLazy<T>,async_simple::coro::RescheduleLazy<double>,async_simple::coro::RescheduleLazy<std::basic_string<char,std::char_traits<char>,std::allocator<char>>>)”的引用
          with
          [
              T=int
          ]
D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1022): warning C4305: “if”: 从“size_t”到“bool”截断
  D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1022): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAll<async_simple::coro::RescheduleLazy,T,void,void>(async_simple::coro::RescheduleLazy<T>,async_simple::coro::RescheduleLazy<void>,async_simple::coro::RescheduleLazy<void>)”的引用
          with
          [
              T=int
          ]
D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1103): warning C4305: “if”: 从“size_t”到“bool”截断
  D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1103): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAllPara<async_simple::coro::Lazy,int,double,std::basic_string<char,std::char_traits<char>,std::allocator<char>>,std::thread::id,std::thread::id>(async_simple::coro::Lazy<int>,async_simple::coro::Lazy<double>,async_simple::coro::Lazy<std::basic_string<char,std::char_traits<char>,std::allocator<char>>>,async_simple::coro::Lazy<std::thread::id>,async_simple::coro::Lazy<std::thread::id>)”的引用
D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1225): warning C4305: “if”: 从“size_t”到“bool”截断
  D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1225): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAny<async_simple::coro::Lazy,short,unsigned short,int,unsigned int,long,unsigned long,__int64,unsigned __int64>(async_simple::coro::Lazy<short>,async_simple::coro::Lazy<unsigned short>,async_simple::coro::Lazy<int>,async_simple::coro::Lazy<unsigned int>,async_simple::coro::Lazy<long>,async_simple::coro::Lazy<unsigned long>,async_simple::coro::Lazy<__int64>,async_simple::coro::Lazy<unsigned __int64>)”的引用
D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1264): warning C4305: “if”: 从“size_t”到“bool”截断
  D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1264): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAny<async_simple::coro::RescheduleLazy,T,unsigned short,int,unsigned int,long,unsigned long,__int64,unsigned __int64>(async_simple::coro::RescheduleLazy<T>,async_simple::coro::RescheduleLazy<unsigned short>,async_simple::coro::RescheduleLazy<int>,async_simple::coro::RescheduleLazy<unsigned int>,async_simple::coro::RescheduleLazy<long>,async_simple::coro::RescheduleLazy<unsigned long>,async_simple::coro::RescheduleLazy<__int64>,async_simple::coro::RescheduleLazy<unsigned __int64>)”的引用
          with
          [
              T=short
          ]
D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1300): warning C4305: “if”: 从“size_t”到“bool”截断
  D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1300): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAny<async_simple::coro::RescheduleLazy,T,T,std::vector<int,std::allocator<int>>,std::vector<double,std::allocator<double>>,std::set<int,std::less<int>,std::allocator<int>>>(async_simple::coro::RescheduleLazy<T>,async_simple::coro::RescheduleLazy<T>,async_simple::coro::RescheduleLazy<std::vector<int,std::allocator<int>>>,async_simple::coro::RescheduleLazy<std::vector<double,std::allocator<double>>>,async_simple::coro::RescheduleLazy<std::set<int,std::less<int>,std::allocator<int>>>)”的引用
          with
          [
              T=std::basic_string<char,std::char_traits<char>,std::allocator<char>>
          ]
  ninja: build stopped: subcommand failed.

全部生成 失败。

这是vs编译的报错信息

**Comment by ChuanqiXu9** [comment]
@poor-circle 我没有 windows 环境，有空的话帮忙看看吧

**Comment by poor-circle** [comment]
> @poor-circle 我没有 windows 环境，有空的话帮忙看看吧
ok

**Comment by poor-circle** [comment]
### cmake手动安装：
首先安装Visual Studio 2022的C++与cmake组件，然后按以下命令编译
```sh
cd async_simple
md build
cd build
cmake.exe .. -DASYNC_SIMPLE_ENABLE_TESTS=OFF -DASYNC_SIMPLE_BUILD_DEMO_EXAMPLE=OFF
cmake.exe --build . --config Release
cmake.exe --install --prefix .\install_path
```
async_simple已经安装在`install_path`下。
在不使用uthread的情况下，async_simple是header only的，只需要将install_path下的include文件夹传递给编译器即可。
如果需要使用uthread，则需要链接install_path下的async_simple.lib。
### xmake：
async_simple可以通过xmake自带的包管理器来安装，请参考xmake文档。

**Comment by poor-circle** [comment]
> ### cmake手动安装：
> 首先安装Visual Studio 2022的C++与cmake组件，然后按以下命令编译
> 
> ```shell
> cd async_simple
> md build
> cd build
> cmake.exe .. -DASYNC_SIMPLE_ENABLE_TESTS=OFF -DASYNC_SIMPLE_BUILD_DEMO_EXAMPLE=OFF
> cmake.exe --build . --config Release
> cmake.exe --install --prefix .\install_path
> ```
> 
> async_simple已经安装在`install_path`下。 在不使用uthread的情况下，async_simple是header only的，只需要将install_path下的include文件夹传递给编译器即可。 如果需要使用uthread，则需要链接install_path下的async_simple.lib。
> 
> ### xmake：
> async_simple可以通过xmake自带的包管理器来安装，请参考xmake文档。

visual studio自带的cmake路径可能类似于`C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe`

另外一种方式是将async_simple直接作为cmake工程在visual studio中打开并编译。

**Comment by 4kangjc** [comment]
> [60/62] Linking CXX executable demo_example\http_client.exe [61/62] Building CXX object async_simple\coro\test\CMakeFiles\async_simple_coro_test.dir\LazyTest.cpp.obj FAILED: async_simple/coro/test/CMakeFiles/async_simple_coro_test.dir/LazyTest.cpp.obj "E:\visual studio\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe" /nologo /TP -DASYNC_SIMPLE_HAS_NOT_AIO -ID:\c++\async4\async_simple-main -external:I D:\c++\async4\async_simple-main\out\build\x64-Debug_deps\googletest-src\googletest\include -external:I D:\c++\async4\async_simple-main\out\build\x64-Debug_deps\googletest-src\googlemock\include -external:I D:\c++\async4\async_simple-main\out\build\x64-Debug_deps\googletest-src\googletest -external:I D:\c++\async4\async_simple-main\out\build\x64-Debug_deps\googletest-src\googlemock -external:W0 /std:c++20 /Zc:__cplusplus /await:strict /EHa /Zi /Ob0 /Od /RTC1 /MTd -MDd -std:c++20 /showIncludes /Foasync_simple\coro\test\CMakeFiles\async_simple_coro_test.dir\LazyTest.cpp.obj /Fdasync_simple\coro\test\CMakeFiles\async_simple_coro_test.dir\ /FS -c D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp D:\c++\async4\async_simple-main\out\build\x64-Debug\cl : 命令行 warning D9025: 正在重写“/MTd”(用“/MDd”) D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(930): warning C4305: “if”: 从“size_t”到“bool”截断 D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(930): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAll<async_simple::coro::Lazy,int,double,std::basic_string<char,std::char_traits,std::allocator>>(async_simple::coro::Lazy,async_simple::coro::Lazy,async_simple::coro::Lazy<std::basic_string<char,std::char_traits,std::allocator>>)”的引用 D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(957): warning C4305: “if”: 从“size_t”到“bool”截断 D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(957): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAll<async_simple::coro::Lazy,int,void,void>(async_simple::coro::Lazy,async_simple::coro::Lazy,async_simple::coro::Lazy)”的引用 D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(996): warning C4305: “if”: 从“size_t”到“bool”截断 D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(996): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAll<async_simple::coro::RescheduleLazy,T,double,std::basic_string<char,std::char_traits,std::allocator>>(async_simple::coro::RescheduleLazy,async_simple::coro::RescheduleLazy,async_simple::coro::RescheduleLazy<std::basic_string<char,std::char_traits,std::allocator>>)”的引用 with [ T=int ] D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1022): warning C4305: “if”: 从“size_t”到“bool”截断 D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1022): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAll<async_simple::coro::RescheduleLazy,T,void,void>(async_simple::coro::RescheduleLazy,async_simple::coro::RescheduleLazy,async_simple::coro::RescheduleLazy)”的引用 with [ T=int ] D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1103): warning C4305: “if”: 从“size_t”到“bool”截断 D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1103): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAllPara<async_simple::coro::Lazy,int,double,std::basic_string<char,std::char_traits,std::allocator>,std:🧵:id,std:🧵:id>(async_simple::coro::Lazy,async_simple::coro::Lazy,async_simple::coro::Lazy<std::basic_string<char,std::char_traits,std::allocator>>,async_simple::coro::Lazystd:🧵:id,async_simple::coro::Lazystd:🧵:id)”的引用 D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1225): warning C4305: “if”: 从“size_t”到“bool”截断 D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1225): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAny<async_simple::coro::Lazy,short,unsigned short,int,unsigned int,long,unsigned long,__int64,unsigned __int64>(async_simple::coro::Lazy,async_simple::coro::Lazy,async_simple::coro::Lazy,async_simple::coro::Lazy,async_simple::coro::Lazy,async_simple::coro::Lazy,async_simple::coro::Lazy<__int64>,async_simple::coro::Lazy)”的引用 D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1264): warning C4305: “if”: 从“size_t”到“bool”截断 D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1264): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAny<async_simple::coro::RescheduleLazy,T,unsigned short,int,unsigned int,long,unsigned long,__int64,unsigned __int64>(async_simple::coro::RescheduleLazy,async_simple::coro::RescheduleLazy,async_simple::coro::RescheduleLazy,async_simple::coro::RescheduleLazy,async_simple::coro::RescheduleLazy,async_simple::coro::RescheduleLazy,async_simple::coro::RescheduleLazy<__int64>,async_simple::coro::RescheduleLazy)”的引用 with [ T=short ] D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1300): warning C4305: “if”: 从“size_t”到“bool”截断 D:\c++\async4\async_simple-main\async_simple\coro\test\LazyTest.cpp(1300): note: 查看对正在编译的函数 模板 实例化“auto async_simple::coro::collectAny<async_simple::coro::RescheduleLazy,T,T,std::vector<int,std::allocator>,std::vector<double,std::allocator>,std::set<int,std::less,std::allocator>>(async_simple::coro::RescheduleLazy,async_simple::coro::RescheduleLazy,async_simple::coro::RescheduleLazy<std::vector<int,std::allocator>>,async_simple::coro::RescheduleLazy<std::vector<double,std::allocator>>,async_simple::coro::RescheduleLazy<std::set<int,std::less,std::allocator>>)”的引用 with [ T=std::basic_string<char,std::char_traits,std::allocator> ] ninja: build stopped: subcommand failed.
> 
> 全部生成 失败。
> 
> 这是vs编译的报错信息

应该是lazy test的编译出了问题，但这里我没有看到error的信息，最简单的方式是你暂时注释掉`async_simple/coro/test/LazyTest.cpp`的代码

**Comment by poor-circle** [comment]
@ChuanqiXu9 在支持vcpkg以后，我们应该可以关掉这个issue了
