### ISSUE TITLE
 Does the opts.prompt semantics not allow in-place execution?

### ISSUE THREAD

**Issue by bbbgan** [alibaba/async_simple#312]
### Search before asking

- [✔ ] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
在文档的这里，说到opts.prompt为true时，不能原地执行，我对此的理解是无论如何，都应该被调度，而不是因为在执行线程中就直接执行
https://github.com/alibaba/async_simple/blob/7caf98b95f7140302b89483c38e1cc5f13e25233/docs/docs.cn/Executor.md?plain=1#L48
但是根据代码，当 opts.prompt 为 true的时候，应该是可以直接执行的，为false才是不能原地执行，必须进入调度。我想知道我是否理解的有问题。
```c++
bool SimpleExecutor::checkin(Func func, Context ctx, ScheduleOptions opts) {
    int64_t id = reinterpret_cast<int64_t>(ctx);
    auto prompt = _pool.getCurrentId() == (id & (~kContextMask)) && opts.prompt;
    if (prompt) {
        func();
        return true;
    }
    return _pool.scheduleById(std::move(func), id & (~kContextMask)) ==
           util::ThreadPool::ERROR_NONE;
}
```

### Are you willing to submit a PR?

- [✔ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
这里应该是文档写错了
