### ISSUE TITLE
We need functionality similar to asio::dispatch

### ISSUE THREAD

**Issue by chloro-pn** [alibaba/async_simple#314]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
`asio::dispatch`可以让协程将自己调度到指定的`executor`中，用户在实现相同逻辑时可以减少一些不必要的封装和抽象。

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
Closed with https://github.com/alibaba/async_simple/pull/315
