### ISSUE TITLE
xmake build failed on windows

### ISSUE THREAD

**Issue by Zhou-Pixel** [alibaba/async_simple#318]
![image](https://github.com/alibaba/async_simple/assets/72525794/d4efd4dd-7819-4380-91c4-03bec7861871)

**Comment by ChuanqiXu9** [comment]
async_simple的xmake对modules的支持是实验性的，同时我们之前的实验是在Linux上做的。所以我们应该不会去看这个问题。

对 Windows 上的 modules 感兴趣的话可以去 xmake 或者 cmake 社区看文档后自己上手试试。

**Comment by waruqi** [comment]
这个 project 用了 libaio ，它只支持 linux，应该没法在 windows 上编译过。

**Comment by ChuanqiXu9** [comment]
我们在 windows 上编译时会把 libaio 相关的东西关掉，在 CMake 里用 `-DASYNC_SIMPLE_DISABLE_AIO=ON` 做适配。但没有特别对 xmake 做适配

**Comment by waruqi** [comment]
@Zhou-Pixel 应该可以了，可以再试试 https://github.com/alibaba/async_simple/pull/320#issuecomment-1580044047
