### ISSUE TITLE
a bug in specifying executors for Future

### ISSUE THREAD

**Issue by chloro-pn** [alibaba/async_simple#325]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
```c++
    async_simple::executors::SimpleExecutor ex1(2);
    async_simple::executors::SimpleExecutor ex2(2);
    auto lazy1 = [&]() -> Lazy<> {
        Promise<int> pr;
        Executor* current_ex = co_await CurrentExecutor{};
        EXPECT_EQ(current_ex, &ex1);
        auto fut = pr.getFuture().via(&ex2);
        sum(1, 1, [pr = std::move(pr)](int val) mutable { pr.setValue(val); });
        std::this_thread::sleep_for(std::chrono::milliseconds(500));
        auto val = co_await std::move(fut);
        EXPECT_EQ(2, val);
        current_ex = co_await CurrentExecutor{};
        // expect failed
        EXPECT_EQ(current_ex, &ex2);
    };
    syncAwait(lazy1().via(&ex1));
    std::this_thread::sleep_for(std::chrono::milliseconds(1000));
```
给Future指定Executor，`co_await Future`返回之后协程记录的Executor和调度该协程的Executor不一致。

原因见注释：
```c++
    void scheduleContinuation(bool triggerByContinuation) {
        logicAssert(
            _state.load(std::memory_order_relaxed) == detail::State::DONE,
            "FutureState is not DONE");
        if (!_forceSched && (!_executor || triggerByContinuation ||
                             currentThreadInExecutor())) {
            // execute inplace for better performance
            ContinuationReference guard(this);
            _continuation(std::move(_try_value));
        } else {
            ContinuationReference guard(this);
            ContinuationReference guardForException(this);
            try {
                bool ret;
                if (Executor::NULLCTX == _context) {
                    // *******************************
                    // _executor只调度，不更新协程记录的executor
                    ret = _executor->schedule(
                        [fsRef = std::move(guard)]() mutable {
                            auto ref = std::move(fsRef);
                            auto fs = ref.getFutureState();
                            fs->_continuation(std::move(fs->_try_value));
                        });
                } else {
                    ScheduleOptions opts;
                    opts.prompt = !_forceSched;
                    // schedule continuation in the same context before
                    // checkout()
                    // *******************************
                    // _executor只调度，不更新协程记录的executor
                    ret = _executor->checkin(
                        [fsRef = std::move(guard)]() mutable {
                            auto ref = std::move(fsRef);
                            auto fs = ref.getFutureState();
                            fs->_continuation(std::move(fs->_try_value));
                        },
                        _context, opts);
                }
                if (!ret) {
                    throw std::runtime_error(
                        "schedule continuation in executor failed");
                }
            } catch (std::exception& e) {
                // reschedule failed, execute inplace
                _continuation(std::move(_try_value));
            }
        }
    }
```
### Anything else
我们应该将涉及到协程在启动后重新调度的代码封装到dispatch函数中（需要加一个非协程上下文环境的dispatch函数），
统一处理同步协程记录的Executor、调度失败确保抛异常等逻辑，这样如果后续要加监控/日志，也更清晰。

不过这里coroutine_handle已经被擦除了。翻了下源码，Future组件应该是在有栈协程、无栈协程、非协程环境下都能使用，回调函数统一在`std::function<void(Try<T>&& value)>`中存储，我不熟悉uthread的代码不太好改。

这里先做个记录，不急的话后面在改呗。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
我感觉不算bug吧？future.via(ex2) 的语义只是指定 future 到 ex2 中执行，和返回后的环境没啥关系吧？我感觉这里还算 well defined

**Comment by chloro-pn** [comment]
emmm，文档里是这么说的：

> 如果 Future 已经设置过 Executor，那么此时当前协程的 Resumption 由该调度器控制。

它的实现是这样：
```c++
template <typename T>
auto operator co_await(Future<T>&& future) {
    struct FutureAwaiter {
        Future<T> future_;

        bool await_ready() { return future_.hasResult(); }
        void await_suspend(coro::CoroHandle<> continuation) {
            future_.setContinuation(
                [continuation](Try<T>&& t) mutable { continuation.resume(); });
        }
        auto await_resume() { return std::move(future_.value()); }
    };

    return FutureAwaiter{std::move(future)};
}
```
从实现上来说貌似就是将协程调度到指定executor上执行了，你的意思是为Future指定Executor的语义是：将唤醒等待协程这一逻辑交给指定的executor调度，但是唤醒之后协程应该还在原来绑定的executor上调度么

**Comment by ChuanqiXu9** [comment]
> 从实现上来说貌似就是将协程调度到指定executor上执行了，你的意思是为Future指定Executor的语义是：将唤醒等待协程这一逻辑交给指定的executor调度，但是唤醒之后协程应该还在原来绑定的executor上调度么

是的。FutureAwaiter 没有实现 coAwait，所以会去走 viaAwaiter 的逻辑。这个是 by design 的

> emmm，文档里是这么说的：
>> 如果 Future 已经设置过 Executor，那么此时当前协程的 Resumption 由该调度器控制。

这句话的本意是当前协程何时唤醒由该调度器控制，可能有点歧义，我之后改改。

**Comment by chloro-pn** [comment]
> 



> > 从实现上来说貌似就是将协程调度到指定executor上执行了，你的意思是为Future指定Executor的语义是：将唤醒等待协程这一逻辑交给指定的executor调度，但是唤醒之后协程应该还在原来绑定的executor上调度么
> 
> 是的。FutureAwaiter 没有实现 coAwait，所以会去走 viaAwaiter 的逻辑。这个是 by design 的。我之后加个注释吧。
> 
> > emmm，文档里是这么说的：
> > > 如果 Future 已经设置过 Executor，那么此时当前协程的 Resumption 由该调度器控制。
> 
> 这句话的本意是当前协程何时唤醒由该调度器控制，可能有点歧义，我之后改改。

哦哦我明白了，viaAwaiter 会调度回原executor，我搞混了。

**Comment by chloro-pn** [comment]
> > 从实现上来说貌似就是将协程调度到指定executor上执行了，你的意思是为Future指定Executor的语义是：将唤醒等待协程这一逻辑交给指定的executor调度，但是唤醒之后协程应该还在原来绑定的executor上调度么
> 
> 是的。FutureAwaiter 没有实现 coAwait，所以会去走 viaAwaiter 的逻辑。这个是 by design 的。我之后加个注释吧。
> 
> > emmm，文档里是这么说的：
> > > 如果 Future 已经设置过 Executor，那么此时当前协程的 Resumption 由该调度器控制。
> 
> 这句话的本意是当前协程何时唤醒由该调度器控制，可能有点歧义，我之后改改。

emmmm可以问下这里为什么走viaAwaiter 的逻辑么，感觉可以避免调viaAwaiter后面的开销，毕竟Future作为沟通有栈无栈协程和非协程环境的工具，性能还是要考虑的（从Future的实现上也能看出来）。

**Comment by ChuanqiXu9** [comment]
有道理，应该就是之前思维定式了，这里避免掉 viacoroutine 肯定更好些

**Comment by chloro-pn** [comment]
嗯嗯，我来试试优化一下

**Comment by RainMark** [comment]
看了下后续mr，大概懂了。

**Comment by chloro-pn** [comment]
> future 默认还是需要走via coroutine吧，不然用future来在coroutine中对接普通callback岂不是默认后续就不回到之前所在线程？

这里把回到之前线程的逻辑放在FutureAwaiter的suspend里了，是保证语义不变的，就是减少了via coroutine的开销。我觉得future是内部组件，没必要走via coroutine的。
[源码在这里](https://github.com/alibaba/async_simple/blob/main/async_simple/coro/FutureAwaiter.h#L43)

**Comment by RainMark** [comment]
> > future 默认还是需要走via coroutine吧，不然用future来在coroutine中对接普通callback岂不是默认后续就不回到之前所在线程？
> 
> 这里把回到之前线程的逻辑放在FutureAwaiter的suspend里了，是保证语义不变的，就是减少了via coroutine的开销。我觉得future是内部组件，没必要走via coroutine的。 [源码在这里](https://github.com/alibaba/async_simple/blob/main/async_simple/coro/FutureAwaiter.h#L43)

嗯嗯，看到了，没问题，对外语义没变。赞！
