### ISSUE TITLE
Remove util/Condition.h

### ISSUE THREAD

**Issue by RainMark** [alibaba/async_simple#33]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

util/Condition.h like c++ std::condition_variable, we better use std::condition_variable to keep cross platform

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
Done.

**Comment by 4kangjc** [comment]
现在的语义是信号量？

**Comment by 4kangjc** [comment]
> 现在的语义是信号量？

https://en.cppreference.com/w/cpp/thread/counting_semaphore

**Comment by ChuanqiXu9** [comment]
> > 现在的语义是信号量？
> 
> https://en.cppreference.com/w/cpp/thread/counting_semaphore

是的，现在是在 std::condition_variable 上简单包了一层

**Comment by 4kangjc** [comment]
> > > 现在的语义是信号量？
> > 
> > 
> > https://en.cppreference.com/w/cpp/thread/counting_semaphore
> 
> 是的，现在是在 std::condition_variable 上简单包了一层

```cpp
class Condition : public std::binary_semaphore {
public:
    explicit Condition(ptrdiff_t num = 0) : std::binary_semaphore(num) {}
};
```
可惜某些编译器还不太能支持binary_semaphore

**Comment by ChuanqiXu9** [comment]
> https://en.cppreference.com/w/cpp/thread/counting_semaphore

这样，不过我觉得这个倒是影响不大；不过感兴趣的话可以新开个 issue 来 track
