### ISSUE TITLE
What about add a new feature lazy_local

### ISSUE THREAD

**Issue by chloro-pn** [alibaba/async_simple#332]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
一个新的特性lazy_local，可以存储数据，就像线程环境中的thread_local一样，具有调用关系的lazy间可以方便的共享lazy_local中的数据。这个特性主要的意义在于**可以在框架层向Lazy调用栈共享一些数据，应用层几乎不需要感知（至少不需要感染Lazy入参和返回值类型）**。
但是这个特性需要入侵式的修改Lazy（Lazy持有lazy_local和持有Executor在实现上应该比较相似，至少需要在Lazy中新加一个数据成员），这个可以接受不。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
这个我们想过，比较好的方式是在 promise_type 里增加一个 void* 指针。该指针指向的内容由具体用户决定。我们觉得这样可能好一些

**Comment by chloro-pn** [comment]
嗯，需要一个兼容性比较好的设计，我给一个最初的版本：

* 只允许向RescheduleLazy绑定lazy_local，随着调用栈传递给Lazy；
* Lazy启动RescheduleLazy默认不传递lazy_local（需要的话由用户手动指定，同时用户保证多线程访问是安全的）；
* 当通过start函数启动RescheduleLazy时，加一个回调函数参数来回收lazy_local；
* 当通过syncAwait启动RescheduleLazy时，由用户在调用上下文中回收lazy_local；

**Comment by ChuanqiXu9** [comment]
我觉得仿照 Executor 的设计就好，比如说 Executor 的生命周期由用户管理。随着 co_await 逐层向 Callee 传递即可。其他的限制感觉不是很有必要

**Comment by chloro-pn** [comment]
这里主要是生命周期的问题，Executor和lazy_local在这里是有不同的。如果lazy_local的生命周期交给用户管理的话，意味着用户需要在使用Lazy前预先规划好需要共享的数据，Lazy持有其指针并传递共享，就像Executor一样。
这种方式对Executor是自然的，实际生产环境中Executor的生命周期总是大于Lazy，这由它的本质特点决定，**我们需要将Lazy交由Executor调度**。因此我们不会在协程环境中定义Executor的局部变量，而是会统一规划好一组Executor，Lazy持有其指针进行调度。
但是对于lazy_local而言，很多时候是没有办法，也并不需要提前规划的，比如在一个较长的调用链a->b->c->...->e中，我们需要在e中异步启动一个RescheduleLazy，并为其绑定lazy_local变量，当该RescheduleLazy完成时就释放lazy_local资源，这个逻辑不应该被a、b、c所感知。
我感觉Executor和lazy_local在作用域和管理方式上类似，但是有一个不同点就是，**Lazy不需要关注Executor的生命周期，但是需要关注lazy_local的生命周期，这是由它们的使用特点决定的。**

**Comment by ChuanqiXu9** [comment]
我感觉有些 overdesign 了，仿照 thread_local 或者有栈协程的 fiber_local 的话，函数访问这些变量时都不用考虑生命周期的问题的。

> 比如在一个较长的调用链a->b->c->...->e中，我们需要在e中异步启动一个RescheduleLazy，并为其绑定lazy_local变量，当该RescheduleLazy完成时就释放lazy_local资源

这样的话可以这么写：

```
Lazy<...> e() {
     AnyLazyLocalType l = new ...;
     AnyAsyncTask().via(E).setLazyLocal(l).start([l](auto &&t){
         delete l;
     });
}
```

**Comment by chloro-pn** [comment]
> 我感觉有些 overdesign 了，仿照 thread_local 或者有栈协程的 fiber_local 的话，函数访问这些变量时都不用考虑生命周期的问题的。
> 
> > 比如在一个较长的调用链a->b->c->...->e中，我们需要在e中异步启动一个RescheduleLazy，并为其绑定lazy_local变量，当该RescheduleLazy完成时就释放lazy_local资源
> 
> 这样的话可以这么写：
> 
> ```
> Lazy<...> e() {
>      AnyLazyLocalType l = new ...;
>      AnyAsyncTask().via(E).setLazyLocal(l).start([l](auto &&t){
>          delete l;
>      });
> }
> ```

哦哦明白了
