### ISSUE TITLE
There might be better to use like `asyncio.gather` in example of `StacklessCoroutineAndFuture.md`

### ISSUE THREAD

**Issue by faker2048** [alibaba/async_simple#359]
https://github.com/alibaba/async_simple/blob/main/docs/docs.en/StacklessCoroutineAndFuture.md

This is an amazing C++20 project. But in this document, I would like to use like `asycio.gather` to better highlight the advantages of coroutines. Even in this example, IO can potentially be parallel (files are on different disks, and a single disk cannot fully utilize the system's IO or the files are on different machines).

**Comment by ChuanqiXu9** [comment]
Thanks for reading this. But I don't get your points. Feel free to send a PR for any suggestion.
