### ISSUE TITLE
GTEST_INCLUDE_DIR-NOTFOUND

### ISSUE THREAD

**Issue by yinghaoyu** [alibaba/async_simple#363]
`gtest` had already been installed at `/usr/local/inclde/gtest`，running `cmake ..` at directory `aysnc_simple/build` show like this:
```bash
CMake Error in async_simple/CMakeLists.txt:
  Found relative path while evaluating include directories of "async_simple":

    "GTEST_INCLUDE_DIR-NOTFOUND"
```

**Comment by ChuanqiXu9** [comment]
The logic to find Gtest is https://github.com/alibaba/async_simple/blob/b3d765860023a574a3b725cfb361fa078b2a821a/cmake/FindGTest.cmake#L1-L43. You can look at the script and your local settings to find what's going wrong.

**Comment by yinghaoyu** [comment]
Thanks. It's ok now.
