### ISSUE TITLE
相比于老式的异步编程, switch延时如何?

### ISSUE THREAD

**Issue by JaydenFish** [alibaba/async_simple#379]
请教一下, C++20的无栈协程相比于老式的异步编程(std::function的callback)模式, 哪个延时更低?
我这行业业务并没有那么复杂, 但是对性能要求很高.

**Comment by ChuanqiXu9** [comment]
相比于老异步模式，无栈协程没有决定性的性能优势，只是相对来说可以提供更多的编译器优化机会，应该只是常数级别的优化。

无栈协程最大的优势还是可以写出更易读，更好维护的代码

**Comment by nqf** [comment]
协程性能不会比回调高，最大优势就是解决了回调地狱
