### ISSUE TITLE
[feature request]使用自定义的LazyPromise的operator new以支持开发者自己提供的allocator

### ISSUE THREAD

**Issue by LXYan2333** [alibaba/async_simple#392]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues. 

### What happened + What you expected to happen

[https://en.cppreference.com/w/cpp/language/coroutines#Dynamic_allocation](https://en.cppreference.com/w/cpp/language/coroutines#Dynamic_allocation)提到开发者可以通过提供自定义的operator new来控制promise对象分配内存的位置，请问可以在

https://github.com/alibaba/async_simple/blob/32597cd7b3fe7dba86de7a3268f21283a2f6cd18/async_simple/coro/Lazy.h#L144

LazyPromise类里添加这个函数以支持用户自己提供allocator吗？（就像标准库容器一样）

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by LXYan2333** [comment]
> std 容器添加 allocator 的风格对代码侵入性比较大。一般的需求的话，大多可以通过自定义 operator new/delete 解决。可以看下 jemalloc 和 tcmalloc 是怎么替换 new/delete，然后自己写一个类似的东西我觉得好一些

研究过微软家的mimalloc，靠的是替换全局的operator new

https://github.com/microsoft/mimalloc/blob/2765ec93026f445cad8f38e6b196dd226a1f6e61/include/mimalloc-new-delete.h#L59

标准允许这种做法：https://en.cppreference.com/w/cpp/memory/new/operator_new#Global_replacements 但是不能将替换范围局限起来，必须全局生效。

如果有可能的话，还是希望能通过提供allocator，毕竟一旦涉及到多线程编程，就很难将全局的operator new/delete和coroutine promise专用的operator new/delete区分开了。

**Comment by LXYan2333** [comment]
emm想到可能可以在自定义的全局operator new里面读一个thread_local变量来决定是否使用自定义分配方式，但是感觉这样对整个程序的侵入性也蛮高的，毕竟整个程序只能自定义一个全局operator new

**Comment by ChuanqiXu9** [comment]
```
__attribute__((weak， noinline))
void *async_simple_allocate(std::size_t n) noexcept {
     return nullptr;
}

class LazyPromise
{
    /* ... */
 
    // ensure the use of non-throwing operator-new
    static Lazy get_return_object_on_allocation_failure()
    {
        ...
    }
 
    // custom non-throwing overload of new
    void* [operator new](http://en.cppreference.com/w/cpp/memory/new/operator_new)([std::size_t](http://en.cppreference.com/w/cpp/types/size_t) n) noexcept
    {
        if (void *async_simple_custom_allocated = async_simple_allocate())
             return async_simple_custom_allocated;
        return ::new(n);
    }
};
```

也许我们可以通过这样的方式达成目标吧，用户可以自定义 `async_simple_allocate` 然后在链接时 override  默认的 weak `async_simple_allocate`。我们可能暂时没时间支持这个，你可以本地测试后交个 PR

**Comment by LXYan2333** [comment]
我的想法是，如果希望根据同样的operator new实现不同的内存分配策略，那么应该是避免不了多态的运行时开销的，无非开销是这里的一个if-else，还是用oop多态的一次虚函数跳转。既然如此不如直接把std::pmr::memory_resource作为参数之一传入Lazy（默认参数std::pmr::new_delete_resource），然后利用标准对promise type的operator new开的洞：

> If the Promise type defines a placement form of [operator new](https://en.cppreference.com/w/cpp/memory/new/operator_new) that takes additional parameters, and they match an argument list where the first argument is the size requested (of type [std::size_t](https://en.cppreference.com/w/cpp/types/size_t)) and the rest are the coroutine function arguments, those arguments will be passed to [operator new](https://en.cppreference.com/w/cpp/memory/new/operator_new) (this makes it possible to use [leading-allocator-convention](https://en.cppreference.com/w/cpp/memory/uses_allocator#Uses-allocator_construction) for coroutines).

实现用户自定义内存资源分配promise type，这样可以在cpp语法规则内解决问题，不依赖编译器拓展。

**Comment by ChuanqiXu9** [comment]
这个 idea 之前的提案里也有，但大家意见基本都是这种风格过于丑了，需要一路把 allocator 传下去，我感觉也不太好用。

> 实现用户自定义内存资源分配promise type，这样可以在cpp语法规则内解决问题，不依赖编译器拓展。

这个倒不算编译器扩展，算 C/C++ 生态底层机制了

**Comment by LXYan2333** [comment]
简单尝试了一下（代码比较丑陋），在promise type里分配内存时额外分配sizeof(void*)，用::operator new分配时在结尾存一个nullptr，用pmr时存上内存资源的指针。

```cpp
  void *operator new(std::size_t size, std::pmr::memory_resource *resource,
                     ...) noexcept {
    std::cout << "LazyPromise new with pmr\n";
    std::byte *r =
        static_cast<std::byte *>(resource->allocate(size + sizeof(void *)));
    static_assert(sizeof(bool) == sizeof(std::byte));
    *reinterpret_cast<void **>(r + size) = resource;
    return r;
  }

  void *operator new(std::size_t size) noexcept {
    std::cout << "LazyPromise new with ::operator new\n";
    std::byte *r =
        static_cast<std::byte *>(::operator new(size + sizeof(void *)));
    static_assert(sizeof(bool) == sizeof(std::byte));
    *reinterpret_cast<void **>(r + size) = nullptr;
    return r;
  }

  void operator delete(void *ptr, std::size_t size) noexcept {
    std::byte *r = static_cast<std::byte *>(ptr);
    if (*reinterpret_cast<void **>(r + size) == nullptr) {
      std::cout << "operator delete with ::operator delete\n";
      ::operator delete(ptr);
    } else {
      std::cout << "operator delete with pmr\n";
      static_cast<std::pmr::memory_resource *>(
          *reinterpret_cast<void **>(r + size))
          ->deallocate(r, size + sizeof(void *));
    }
  }

```

然后用户可以这样调用：

```cpp
async_simple::coro::Lazy<int> foo(std::pmr::memory_resource *resource) {
  co_return 10;
}

async_simple::coro::Lazy<int> foo() { co_return 11; }

async_simple::coro::Lazy<int> foo(std::pmr::memory_resource *resource, int i) {
  co_return i;
}

int main() {
  auto val = async_simple::coro::syncAwait(foo(std::pmr::get_default_resource()));
  auto val2 = async_simple::coro::syncAwait(foo());
  auto val3 = async_simple::coro::syncAwait(foo(std::pmr::get_default_resource(), 12)); //打印LazyPromise new
  return val + val2 + val3;
}
```

输出：

```
LazyPromise new with pmr
operator delete with pmr
LazyPromise new with ::operator new
operator delete with ::operator delete
LazyPromise new with pmr
operator delete with pmr
```

这样不关心分配位置的用户可以沿用原本的写法，API可以与原来保持一致，想要控制内存分配位置的用户可以在第一个参数传入memroy resource，应该还是可行的。

**Comment by LXYan2333** [comment]
好像复杂了一点，默认new时直接存`std::pmr::get_default_resource()`就行了，delete时还能少一次判断。

**Comment by ChuanqiXu9** [comment]
BTW, 看上去最理想的解决方案是 https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2719r1.html

**Comment by ChuanqiXu9** [comment]
> 好像复杂了一点，默认new时直接存`std::pmr::get_default_resource()`就行了，delete时还能少一次判断。

我觉得也行吧。但我觉得比起直接用 std::pmr，得 async_simple 自己封一层会好一些

**Comment by LXYan2333** [comment]
> BTW, 看上去最理想的解决方案是 https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2719r1.html

这提案太新了，感觉3年内都用不上

**Comment by LXYan2333** [comment]
> 我觉得也行吧。但我觉得比起直接用 std::pmr，得 async_simple 自己封一层会好一些

可以请问一下原因吗？因为pmr 17就有了，coroutine是20的，用这个库的用户肯定能用上pmr了吧。

**Comment by ChuanqiXu9** [comment]
> > 我觉得也行吧。但我觉得比起直接用 std::pmr，得 async_simple 自己封一层会好一些
> 
> 可以请问一下原因吗？因为pmr 17就有了，coroutine是20的，用这个库的用户肯定能用上pmr了吧。

可以看下 https://github.com/alibaba/async_simple/blob/main/async_simple/experimental/coroutine.h。语言 feature 和库 feature 是分开的。我们要求相对高版本的编译器，但对于标准库版本的要求则可以相对低一些。但标准库版本不提供 coroutine 时，我们就用自己定义的。

**Comment by LXYan2333** [comment]
有道理，那我试着写一个pr吧。

**Comment by LXYan2333** [comment]
我跑了一下测试，async_simple_executor_test这个测试跑不过，但是我切换到目前的main分支也没跑过，请问这个测试是不是暂时坏了？

**Comment by 4kangjc** [comment]
有Promise Allocator
https://github.com/alibaba/async_simple/blob/main/async_simple/coro/PromiseAllocator.h

**Comment by LXYan2333** [comment]
> 有Promise Allocator https://github.com/alibaba/async_simple/blob/main/async_simple/coro/PromiseAllocator.h

但是并不能直接`class LazyPromiseBase : public PromiseAllocator<void>`，因为LazyPromiseBase的所有子类都定义了get_return_object_on_allocation_failure函数，要求new与delete都是noexcept的。
