### ISSUE TITLE
Cleanup Executor.h

### ISSUE THREAD

**Issue by RainMark** [alibaba/async_simple#40]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

The Executor.h's `syncSchedule()` and `Awaitable schedule();` method never used, we should delete it?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
schedule is used in [demo example](https://github.com/alibaba/async_simple/blob/main/demo_example/asio_util.hpp#L62)

**Comment by RainMark** [comment]
> schedule is used in [demo example](https://github.com/alibaba/async_simple/blob/main/demo_example/asio_util.hpp#L62)

sorry, i mean `Awaitable schedule();`

**Comment by ChuanqiXu9** [comment]
If they are never used, I prefer to remove it and add it back once needed.
