### ISSUE TITLE
CountChar build failed in gcc 11.2.1

### ISSUE THREAD

**Issue by vbirds** [alibaba/async_simple#41]
gcc version:
gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE

[ 71%] Built target async_simple
[ 85%] Building CXX object demo_example/CMakeFiles/CountChar.dir/CountChar.cpp.o
In file included from /tmp/tmp.XuLZlZqHI1/async_simple/coro/LazyHelper.h:56,
                 from /tmp/tmp.XuLZlZqHI1/async_simple/coro/Lazy.h:538,
                 from /tmp/tmp.XuLZlZqHI1/demo_example/CountChar.cpp:20:
/tmp/tmp.XuLZlZqHI1/async_simple/coro/Collect.h: In member function ‘void async_simple::coro::detail::CollectAnyAwaiter<LazyType, IAlloc>::await_suspend(std::__n4861::coroutine_handle<void>)’:
/tmp/tmp.XuLZlZqHI1/async_simple/coro/Collect.h:85:13: error: invalid ‘static_cast’ from type ‘std::__n4861::coroutine_handle<void>*’ to type ‘std::__n4861::coroutine_handle<async_simple::coro::detail::LazyPromiseBase>*’
   85 |             static_cast<STD_CORO::coroutine_handle<LazyPromiseBase>*>(
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   86 |                 &continuation)
      |                 ~~~~~~~~~~~~~~
/tmp/tmp.XuLZlZqHI1/async_simple/coro/Collect.h: In member function ‘void async_simple::coro::detail::CollectAllAwaiter<LazyType, IAlloc, OAlloc, Para>::await_suspend(std::__n4861::coroutine_handle<void>)’:
/tmp/tmp.XuLZlZqHI1/async_simple/coro/Collect.h:161:13: error: invalid ‘static_cast’ from type ‘std::__n4861::coroutine_handle<void>*’ to type ‘std::__n4861::coroutine_handle<async_simple::coro::detail::LazyPromiseBase>*’
  161 |             static_cast<STD_CORO::coroutine_handle<LazyPromiseBase>*>(
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  162 |                 &continuation)
      |                 ~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-deprecated-register’ may have been intended to silence earlier diagnostics
gmake[3]: *** [demo_example/CMakeFiles/CountChar.dir/build.make:82: demo_example/CMakeFiles/CountChar.dir/CountChar.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:501: demo_example/CMakeFiles/CountChar.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:508: demo_example/CMakeFiles/CountChar.dir/rule] Error 2
gmake: *** [Makefile:311: CountChar] Error 2

**Comment by ChuanqiXu9** [comment]
This one should be fixed. Give it a try now.
