### ISSUE TITLE
replace usleep for cross platform support

### ISSUE THREAD

**Issue by RainMark** [alibaba/async_simple#54]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

use std::this_thread::sleep_for to replace all usleep

previous discuss at: https://github.com/alibaba/async_simple/pull/51#discussion_r821478998

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
How about add a USleep function in util.h to make minimal modification?

**Comment by RainMark** [comment]
> How about add a USleep function in util.h or common.h to make minimal modification?

nop, all be one line and just used in test
