### ISSUE TITLE
Infinite loop in benchmarks

### ISSUE THREAD

**Issue by ChuanqiXu9** [alibaba/async_simple#69]
### Search before asking

- [x] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen

It looks like the newest commit caused a infinite loop. See https://github.com/alibaba/async_simple/commit/b7b5e1bdc4181ff2dd198de4640e94f30323b024 for details

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by ChuanqiXu9** [comment]
@RainMark would you like to revert it first and run benchmarks locally to find the problem?

**Comment by qicosmos** [comment]
If disable uthread benchmark，the benchmark case will pass, so the latest PR cause the issue.

**Comment by RainMark** [comment]
sorry, i forget to change the Uthread.bench.cpp's get() to await(), I will fix it
