### ISSUE TITLE
Add cmake parameter to avoid compiling test?

### ISSUE THREAD

**Issue by nqf** [alibaba/async_simple#85]
### Search before asking

- [ ] I searched the [issues](https://github.com/alibaba/async_simple/issues) and found no similar issues.

### What happened + What you expected to happen
It needs GTEST when compiling，But many people only want compiled libraries

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by qicosmos** [comment]
I think make gtest and benchmark optional, minimal dependency makes sense.

**Comment by qicosmos** [comment]
Feel free to make a PR :)

**Comment by ChuanqiXu9** [comment]
@nqf Now it could skip testing by specifying `-DASYNC_SIMPLE_ENABLE_TESTS=OFF` in cmake. But testing is always good.

**Comment by nqf** [comment]
> @nqf Now it could skip testing by specifying `-DASYNC_SIMPLE_ENABLE_TESTS=OFF` in cmake. But testing is always good.

Thank you. However, it seems that it is impossible to set whether to compile dynamic library or static library at present.

**Comment by ChuanqiXu9** [comment]
> ms that it is impossible to set whether to compile dynamic library or static library at present.

Why does it is necessary to compile dynamic or static library standalone?

**Comment by nqf** [comment]
>  If want to make it into vcpkg/xmake installation package, I think this is very necessary， 
Because they basically need static libraries

**Comment by ChuanqiXu9** [comment]
> If want to make it into vcpkg/xmake installation package, I think this is very necessary，
> Because they basically need static libraries

We only plans to support cmake now. But it would be greatly appreciated if you are love to support other build systems like vcpkg.
